import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const dictionaries = {
    en: {
        appTitle: "UB KARAOKE",
        myBookings: "My Bookings",
        searchPlaceholder: "Search karaoke...",
        allDistricts: "All Districts",
        anyRating: "Any Rating",
        stars3: "3+ Stars",
        stars4: "4+ Stars",
        stars45: "4.5+ Stars",
        nearMe: "📍 Near Me",
        noVenues: "No venues found matching your criteria.",
        bookNow: "Book Now",
        perHour: "₮ / hr",
        reviews: "Reviews",
        writeReview: "Write a Review",
        postReview: "Post Review",
        shareExperience: "Share your experience...",
        rating: "Rating",
        date: "Date",
        time: "Time",
        duration: "Duration (Hours)",
        total: "Total",
        proceedPayment: "Proceed to Payment",
        confirmPayment: "Confirm Payment",
        transferInstruction: "Please transfer",
        bankName: "Bank: Khan Bank",
        accountName: "Name: UB Karaoke LLC",
        accountNumber: "Account: 5000000000",
        clickConfirm: "Click confirm once transferred.",
        back: "Back",
        confirmTransfer: "Confirm Transfer",
        bookingConfirmed: "Booking Confirmed!",
        reservedMessage: "Your room at {venue} is reserved.",
        done: "Done",
        unknownDistance: "Unknown",
        away: "away",
        selectRoom: "Select Room",
        capacity: "People",
        features: "Features",
        from: "From",
        // Districts
        district_Sukhbaatar: "Sukhbaatar",
        district_Chingeltei: "Chingeltei",
        district_Bayangol: "Bayangol",
        district_Bayanzurkh: "Bayanzurkh",
        district_Songinokhairkhan: "Songinokhairkhan",
        district_KhanUul: "Khan-Uul",
        district_Nalaikh: "Nalaikh",
        district_Bagakhangai: "Bagakhangai",
        district_Baganuur: "Baganuur",
        // New keys
        searchByDistrict: "Search by District",
        roomImage: "Room Image",
        selectStartTime: "Select Start Time",
        venueClosed: "Venue is closed at this time",
        // Specs & Features
        microphones: "Microphones",
        speaker: "Speaker Quality",
        screen: "Screen Size",
        seating: "Seating",
        ac: "AC Control",
        sound: "Soundproofing",
        lighting: "Lighting",
        cleaning: "Cleaning Buffer",
        view360: "360° View",
        partySupport: "Party Support",
        birthdaySetup: "Birthday Setup",
        partyDecoration: "Party Decoration",
        addOns: "Event Add-ons",
        inches: "\"",
        mins: "mins",
        // Filter keys
        filterPartyCapable: "🎉 Party Capable",
        filterCapacity: "Capacity",
        people: "People",
        // Admin Keys
        dashboard: "Dashboard",
        venuesAndRooms: "Venues & Rooms",
        staffUsers: "Staff Users",
        reports: "Reports",
        finance: "Finance",
        settings: "Settings",
        viewPublicSite: "View Public Site",
        loggedInAs: "Logged in as:",
        venueManagement: "Venue Management",
        addBranch: "+ Add Branch",
        closeBranch: "Close Branch",
        reOpen: "Re-open",
        manageRooms: "Manage Rooms",
        rooms: "Rooms",
        closed: "(Closed)",
        actions: "Action",
        addRoom: "Add Room",
        roomName: "Room Name",
        pricePerHour: "Price Per Hour",
        save: "Save",
        delete: "Del",
        areYouSure: "Are you sure?",
        // Login Modal
        customerLogin: "Customer Login",
        signUp: "Sign Up",
        login: "Login",
        logout: "Log out",
        createAccount: "Create Account",
        adminLoginError: "Use Admin Portal for staff login.",
        invalidCredentials: "Invalid credentials",
        allFieldsRequired: "All fields are required",
        email: "Email",
        phone: "Phone",
        emailPlaceholder: "Email Address",
        phonePlaceholder: "Phone Number",
        loginPlaceholder: "Username, Email, or Phone",
        passwordPlaceholder: "Password",
        noAccount: "Don't have an account? ",
        hasAccount: "Already have an account? ",
        // Multi-room booking
        bookingDetails: "Booking Details",
        roomsSelected: "Rooms Selected",
        confirmSelection: "Confirm Selection",
        cancel: "Cancel",
        onlineBookingDisabled: "Online booking temporarily unavailable",
        viewDetails: "View Details",
        bookingClosedMessage: "Online booking is currently disabled for this venue. Please contact us for inquiries."
    },
    mn: {
        appTitle: "UB КАРАОКЕ",
        myBookings: "Миний захиалгууд",
        searchPlaceholder: "Караоке хайх...",
        allDistricts: "Бүх дүүрэг",
        anyRating: "Бүх үнэлгээ",
        signUp: "Бүртгүүлэх",
        login: "Нэвтрэх",
        stars3: "3+ Од",
        stars4: "4+ Од",
        stars45: "4.5+ Од",
        nearMe: "📍 Ойрхон",
        noVenues: "Таны хайлтад тохирох газар олдсонгүй.",
        bookNow: "Захиалах",
        perHour: "₮ / цаг",
        reviews: "Сэтгэгдэл",
        writeReview: "Сэтгэгдэл бичих",
        postReview: "Нийтлэх",
        shareExperience: "Та сэтгэгдлээ хуваалцана уу...",
        rating: "Үнэлгээ",
        date: "Огноо",
        time: "Цаг",
        duration: "Үргэлжлэх цаг",
        total: "Нийт",
        proceedPayment: "Төлбөр төлөх",
        confirmPayment: "Төлбөр баталгаажуулах",
        transferInstruction: "Та доорх данс руу шилжүүлнэ үү",
        bankName: "Банк: Хаан Банк",
        accountName: "Хүлээн авагч: UB Karaoke LLC",
        accountNumber: "Данс: 5000000000",
        clickConfirm: "Шилжүүлсний дараа баталгаажуулах товчийг дарна уу.",
        back: "Буцах",
        confirmTransfer: "Баталгаажуулах",
        bookingConfirmed: "Захиалга баталгаажлаа!",
        reservedMessage: "Таны {venue} дахь захиалга амжилттай.",
        done: "Болсон",
        unknownDistance: "Тодорхойгүй",
        away: "зайтай",
        selectRoom: "Өрөө сонгох",
        capacity: "Хүн",
        features: "Онцлог",
        from: "Эхлэх үнэ",
        // Districts
        district_Sukhbaatar: "Сүхбаатар",
        district_Chingeltei: "Чингэлтэй",
        district_Bayangol: "Баянгол",
        district_Bayanzurkh: "Баянзүрх",
        district_Songinokhairkhan: "Сонгинохайрхан",
        district_KhanUul: "Хан-Уул",
        district_Nalaikh: "Налайх",
        district_Bagakhangai: "Багахангай",
        district_Baganuur: "Багануур",
        // New keys
        searchByDistrict: "Дүүргээр хайх",
        roomImage: "Өрөөний зураг",
        selectStartTime: "Эхлэх цагаа сонгоно уу",
        venueClosed: "Энэ цагт хаалттай байна",
        // Specs & Features
        microphones: "Микрофон",
        speaker: "Хөгжим",
        screen: "Дэлгэц",
        seating: "Суудал",
        ac: "Эйр кондишн",
        sound: "Тусгаарлалт",
        lighting: "Гэрэлтүүлэг",
        cleaning: "Цэвэрлэгээ",
        view360: "360° Зураг",
        partySupport: "Парти боломжтой",
        birthdaySetup: "Төрсөн өдөр",
        partyDecoration: "Баярын чимэглэл",
        addOns: "Нэмэлт үйлчилгээ",
        inches: "\"",
        mins: "минут",
        // Filter keys
        filterPartyCapable: "🎉 Парти хийх",
        filterCapacity: "Хүний тоо",
        people: "Хүн",
        // Admin Keys
        dashboard: "Хяналтын самбар",
        venuesAndRooms: "Салбар & Өрөө",
        staffUsers: "Ажилчид",
        reports: "Тайлан",
        finance: "Санхүү",
        settings: "Тохиргоо",
        logout: "Гарах",
        viewPublicSite: "Вэбсайт руу очих",
        loggedInAs: "Нэвтэрсэн:",
        venueManagement: "Салбар Удирдлага",
        addBranch: "+ Салбар нэмэх",
        closeBranch: "Хаах",
        reOpen: "Нээх",
        manageRooms: "Өрөө удирдах",
        rooms: "Өрөө",
        closed: "(Хаалттай)",
        actions: "Үйлдэл",
        addRoom: "Өрөө нэмэх",
        roomName: "Өрөөний нэр",
        pricePerHour: "Цагийн үнэ",
        save: "Хадгалах",
        delete: "Устгах",
        areYouSure: "Та итгэлтэй байна уу?",
        // Login Modal
        customerLogin: "Нэвтрэх",
        createAccount: "Бүртгэл үүсгэх",
        adminLoginError: "Ажилчид Админ хуудсаар нэвтэрнэ үү.",
        invalidCredentials: "Нэр эсвэл нууц үг буруу байна.",
        allFieldsRequired: "Бүх талбарыг бөглөнө үү.",
        email: "И-мэйл",
        phone: "Утас",
        emailPlaceholder: "И-мэйл хаяг",
        phonePlaceholder: "Утасны дугаар",
        loginPlaceholder: "Нэвтрэх нэр, И-мэйл, Утас",
        passwordPlaceholder: "Нууц үг",
        noAccount: "Бүртгэлгүй юу? ",
        hasAccount: "Бүртгэлтэй юу? ",
        // Multi-room booking
        bookingDetails: "Захиалгын дэлгэрэнгүй",
        roomsSelected: "Өрөө сонгогдсон",
        confirmSelection: "Сонголтыг баталгаажуулах",
        cancel: "Цуцлах",
        onlineBookingDisabled: "Онлайн захиалга түр хаагдсан",
        viewDetails: "Дэлгэрэнгүй харах",
        bookingClosedMessage: "Энэ салбарын онлайн захиалга түр хаагдсан байна. Та холбоо барьж тодруулна уу."
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('mn'); // Default to Mongolian

    const t = (key, params = {}) => {
        let text = dictionaries[language][key] || key;
        Object.keys(params).forEach(param => {
            text = text.replace(`{${param}}`, params[param]);
        });
        return text;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'en' ? 'mn' : 'en');
    };

    return (
        <LanguageContext.Provider value={{ language, t, toggleLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};
