import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const dictionaries = {
    en: {
        appTitle: "UB KARAOKE",
        home: "Home",
        profile: "Profile",
        aboutUs: "About Us",
        faq: "FAQ",
        policy: "Policy",
        myBookings: "My Bookings",
        searchPlaceholder: "Search karaoke...",
        allDistricts: "All Districts",
        anyRating: "Any Rating",
        stars3: "3+ Stars",
        stars4: "4+ Stars",
        stars45: "4.5+ Stars",
        nearMe: "📍 Near Me",
        noVenues: "No places found matching your search.",
        noVenuesDesc: "Try adjusting your filters or search terms to find more results.",
        bookNow: "Book Now",
        perHour: "₮ / hour",
        perHourShort: "/ hour",
        reviews: "Reviews",
        writeReview: "Write a Review",
        postReview: "Post Review",
        shareExperience: "Share your experience...",
        rating: "Rating",
        date: "Date",
        time: "Time",
        duration: "Duration (Hours)",
        total: "Total",
        proceedPayment: "Proceed to Payment",
        confirmPayment: "Confirm Payment",
        transferInstruction: "Please transfer",
        bankName: "Bank: Khan Bank",
        accountName: "Name: UB Karaoke LLC",
        accountNumber: "Account: 5000000000",
        clickConfirm: "Click confirm once transferred.",
        back: "Back",
        confirmTransfer: "Confirm Transfer",
        bookingConfirmed: "Booking Confirmed!",
        reservedMessage: "Your room at {venue} is reserved.",
        done: "Done",
        unknownDistance: "Unknown",
        away: "away",
        selectRoom: "Select Room",
        capacity: "People",
        features: "Features",
        from: "From",
        tapToReveal: "Tap to reveal",
        getDirections: "Get Directions",
        photos: "Photos",
        close: "Close",
        noPhotos: "No photos available",
        deselectRoom: "Deselect",
        // Districts
        district_Sukhbaatar: "Sukhbaatar",
        district_Chingeltei: "Chingeltei",
        district_Bayangol: "Bayangol",
        district_Bayanzurkh: "Bayanzurkh",
        district_Songinokhairkhan: "Songinokhairkhan",
        district_KhanUul: "Khan-Uul",
        district_Nalaikh: "Nalaikh",
        district_Bagakhangai: "Bagakhangai",
        district_Baganuur: "Baganuur",
        // New keys
        searchByDistrict: "Search by District",
        roomImage: "Room Image",
        selectStartTime: "Select Start Time",
        venueClosed: "Venue is closed at this time",
        workingHours: "Working Hours",
        openNow: "OPEN NOW",
        reviewsCount: "Reviews",
        fullSchedule: "Full Weekly Schedule",
        // Specs & Features
        microphones: "Microphones",
        speaker: "Speaker Quality",
        screen: "Screen Size",
        seating: "Seating",
        ac: "AC Control",
        sound: "Soundproofing",
        lighting: "Lighting",
        cleaning: "Cleaning Buffer",
        view360: "360° View",
        partySupport: "Party Support",
        birthdaySetup: "Birthday Setup",
        partyDecoration: "Party Decoration",
        addOns: "Event Add-ons",
        inches: "\"",
        mins: "mins",
        // Filter keys
        filterPartyCapable: "🎉 Party Capable",
        filterCapacity: "Capacity",
        people: "People",
        // Admin Keys
        dashboard: "Dashboard",
        venuesAndRooms: "Venues & Rooms",
        staffUsers: "Staff Users",
        reports: "Reports",
        finance: "Finance",
        settings: "Settings",
        viewPublicSite: "View Public Site",
        loggedInAs: "Logged in as:",
        venueManagement: "Venue Management",
        addBranch: "+ Add Branch",
        closeBranch: "Close Branch",
        reOpen: "Re-open",
        manageRooms: "Manage Rooms",
        rooms: "Rooms",
        closed: "(Closed)",
        actions: "Action",
        addRoom: "Add Room",
        roomName: "Room Name",
        pricePerHour: "Price Per Hour",
        save: "Save",
        delete: "Del",
        areYouSure: "Are you sure?",
        // Admin Navigation
        organizations: "Organizations",
        plans: "Plans",
        branchesAndRooms: "Branches & Rooms",
        bookings: "Bookings",
        subscription: "Subscription",
        pointOfSale: "Point of Sale",
        users: "Users",
        staffs: "Staffs",
        auditLogs: "Audit Logs",
        endSession: "End Session",
        publicSite: "PUBLIC SITE",
        managementContext: "Management context",
        filteringDataText: "Filtering data based on selected branch scope",
        switchOrg: "Org:",
        switchVenue: "Switch venue:",
        allOrganizations: "All Organizations",
        selectBranchContext: "Select Branch Context",
        bookingsManagement: "Bookings Management",
        manageBookingsDesc: "Manage and approve customer bookings for your venues",
        totalBookings: "Total Bookings",
        customer: "Customer",
        venueRoom: "Venue / Room",
        status: "Status",
        approve: "Approve",
        reject: "Reject",
        bookingDetails: "Booking Details",
        customerContact: "Customer Contact",
        startTime: "Start Time",
        endTime: "End Time",
        totalPrice: "Total Price",
        source: "Source",
        notes: "Notes",
        noContact: "No contact",
        noContactInfo: "No contact information available",
        noBookingsFound: "No bookings found.",
        filterByVenue: "Filter by Venue",
        filterByStatus: "Filter by Status",
        allVenues: "All Venues",
        allStatuses: "All Statuses",
        pending: "Pending",
        reserved: "Reserved",
        confirmed: "Confirmed",
        checkedIn: "Checked In",
        completed: "Completed",
        cancelled: "Cancelled",
        search: "Search...",
        reservationNotes: "Notes for your reservation (optional)",
        notesPlaceholder: "Leave a comment related to your booking or additional phone/email for contact info...",
        // Login Modal
        customerLogin: "Customer Login",
        signUp: "Sign Up",
        login: "Login",
        logout: "Log out",
        createAccount: "Create Account",
        adminLoginError: "Use Admin Portal for staff login.",
        invalidCredentials: "Invalid credentials",
        allFieldsRequired: "All fields are required",
        email: "Email",
        phone: "Phone",
        emailPlaceholder: "Email Address",
        phonePlaceholder: "Phone Number",
        loginPlaceholder: "Username, Email, or Phone",
        passwordPlaceholder: "Password",
        noAccount: "Don't have an account? ",
        hasAccount: "Already have an account? ",
        // Multi-room booking
        bookingDetails: "Booking Details",
        roomsSelected: "Rooms Selected",
        confirmSelection: "Confirm Selection",
        confirm: "Confirm",
        cancel: "Cancel",
        onlineBookingDisabled: "Online booking temporarily unavailable",
        viewDetails: "View Details",
        bookingClosedMessage: "Online booking is currently disabled for this venue. Please contact us for inquiries.",
        // Public Pages
        pricingTitle: "Transparent Pricing",
        pricingSubtitle: "Powerful tools for modern karaoke businesses. Choose the plan that fits your scale.",
        mostPopular: "Most Popular",
        contactSales: "Contact Sales",
        getStarted: "Get Started",
        month: "/mo",
        commission: "Commission",
        branches: "Branch(es)",
        unlimitedBranches: "Unlimited Branches",
        upToRooms: "Up to {count} Rooms",
        unlimitedRooms: "Unlimited Rooms",
        bestFor: "Best for {target}",
        digitalBooking: "24/7 Digital Booking",

        aboutTitle: "Revolutionizing Nightlife in Mongolia",
        aboutSubtitle: "We are building the digital infrastructure for Ulaanbaatar's entertainment industry.",
        ourMission: "Our Mission",
        missionText1: "UB Karaoke was founded in 2024 with a singular goal: to digitize the fragmented karaoke booking experience. We connect voice enthusiasts with the city's finest venues through a seamless, premium platform.",
        missionText2: "For venue owners, we provide enterprise-grade management tools to optimize room utilization, track revenue, and wow customers with a modern digital presence.",
        communityFirst: "Community First",
        communityDesc: "Connecting people through music and shared experiences.",
        innovation: "Innovation",
        innovationDesc: "Pushing the boundaries of what a booking platform can be.",
        reliability: "Reliability",
        reliabilityDesc: "Trusted by the biggest karaoke chains in UB.",
        getInTouch: "Get in Touch",

        policyTitle: "Terms & Privacy",
        acceptanceTerms: "Acceptance of Terms",
        acceptanceText: "By accessing and using UB Karaoke, you agree to comply with and be bound by these terms and conditions. We reserve the right to modify these terms at any time without prior notice.",
        bookingCancellation: "Booking & Cancellation",
        cancellationPolicy: "Bookings are confirmed upon receipt of payment or confirmation. Cancellations made at least 2 hours prior to the start time are eligible for a full refund. Late cancellations may incur a fee of up to 50% of the booking value.",
        dataPrivacy: "Data Privacy",
        privacyText: "We value your privacy. We collect basic user information (Name, Phone, Email) solely for booking management and service improvement. Your data is encrypted and stored securely. We do not sell your personal information to third parties.",
        codeOfConduct: "Code of Conduct",
        conductText: "Users are expected to treat venue staff and property with respect. Damages caused to venue equipment (microphones, screens, furniture) will be charged to the user's account.",
        lastUpdated: "Last updated: January 2026",
        iAgreeTo: "I agree to the",
        termsOfService: "Terms of Service",
        privacyPolicy: "Privacy Policy",
        and: "&",

        faqTitle: "Frequently Asked Questions",
        faqSubtitle: "Everything you need to know about UB Karaoke.",
        faq1_q: "How do I book a room?",
        faq1_a: "Simply browse the available venues on our homepage, select a room that fits your group size and budget, choose your time slot, and confirm the booking. You can filter by district, price, and features.",
        faq2_q: "Can I cancel my booking?",
        faq2_a: "Yes, you can cancel your booking through the 'My Bookings' section in your profile. Cancellations made at least 2 hours prior to the reservation time are free of charge.",
        faq3_q: "How do I add my karaoke venue to the platform?",
        faq3_a: "Navigate to the 'Pricing' page and choose a plan (Starter, Growth, or Franchise). Once you sign up, our team will review your application and help you set up your venue within 24 hours.",
        faq4_q: "Is payment secure?",
        faq4_a: "Absolutely. We use industry-standard encryption and trusted payment gateways (QPay, SocialPay) to ensure your transactions are safe. We do not store your credit card details.",
        faq5_q: "Do you offer group discounts?",
        faq5_a: "Discounts are determined by individual venues. Look for 'Special Offer' tags on venue cards or check for venues offering 'Party Packages' in the filters.",
        // Manager Dashboard
        organizationOverview: "Organization Overview",
        aggregatedStats: "Aggregated statistics for:",
        liveStatus: "Live Status",
        organizationName: "Organization",
        orgCode: "Org Code",
        active: "Active",
        inactive: "Inactive",
        plan: "Plan",
        totalBookings: "Bookings",
        awaitingApproval: "awaiting approval",
        branchRevenue: "Branch Revenue",
        activeBranches: "Active Branches",
        quickActions: "Manager Quick Actions",
        manualReservation: "Manual Reservation",
        performanceReport: "Performance Report",
        viewBranchStaff: "View Branch Staff",
        manageBookings: "Manage Bookings",
        editOrgSettings: "Organization Settings",
        description: "Description",
        address: "Address",
        saveChanges: "Save Changes",
        saving: "Saving...",
        assignedBySysadmin: "Assigned by System Admin",
        orgDescPlaceholder: "Brief description of your organization...",
        addressPlaceholder: "Organization address...",
        // QPay Payment
        creatingInvoice: "Creating QPay invoice...",
        amountToPay: "Amount to pay",
        scanQrCode: "Scan QR code with your banking app",
        orOpenBank: "Or open your banking app directly",
        waitingForPayment: "Waiting for payment confirmation...",
        retry: "Retry",
        paymentSuccess: "Payment successful!",
        // Cancel Booking
        cancelBookingHeader: "Cancel Booking",
        cancelBookingMessage: "Are you sure you want to cancel this booking? Cancellation fees may apply.",
        yesCancel: "Yes, Cancel",
        goBack: "Go Back",
        // Booking Errors
        reservationExpired: "Reservation expired. Please try again.",
        bookingFailed: "Booking failed. Please try again.",
        roomAlreadyBooked: "This room is already booked for the selected time.",
        processing: "Processing...",
        staffBookingRestriction: "Staff must use Admin Panel for manual bookings.",
        // Banner & Timer
        actionRequired: "Action Required: Complete Booking",
        completePaymentNow: "Complete Payment Now",
        holdRoomMessage: "Your room is being held. Please complete transfer to avoid cancellation.",
        dismissBanner: "Dismiss Banner",
        expiresIn: "Expires In",
        hurryMessage: "Hurry! Complete your payment to secure this room.",
        // Profile Page
        memberSince: "Member since {year}",
        pts: "PTS",
        rewards: "Rewards",
        history: "History",
        noAvailableSlots: "No Available Slots",
        noUpcomingBookings: "No upcoming bookings",
        roomSelection: "Room Selection",
        hours: "Hours",
        payNow: "PAY NOW",
        timeRemaining: "Time Remaining",
        noBookingHistory: "No booking history",
        goldTier: "Gold Tier",
        currentBalance: "Current Balance",
        pointsToNextTier: "{points} points to next tier",
        editProfile: "Edit Profile",
        fullName: "Full Name",
        phoneNumber: "Phone Number",
        pleaseLogin: "Please log in.",
        backToHome: "Back to Home",
        profileUpdatedSuccess: "Profile updated successfully!",
        profileUpdateFailed: "Failed to update profile: "
    },
    mn: {
        appTitle: "UB КАРАОКЕ",
        home: "Нүүр",
        profile: "Профайл",
        aboutUs: "Бидний тухай",
        faq: "Түгээмэл асуултууд",
        policy: "Үйлчилгээний нөхцөл",
        myBookings: "Миний захиалгууд",
        searchPlaceholder: "Караоке хайх...",
        allDistricts: "Бүх дүүрэг",
        anyRating: "Бүх үнэлгээ",
        signUp: "Бүртгүүлэх",
        login: "Нэвтрэх",
        stars3: "3+ Од",
        stars4: "4+ Од",
        stars45: "4.5+ Од",
        nearMe: "📍 Ойрхон",
        noVenues: "Таны хайлтад тохирох газар олдсонгүй.",
        noVenuesDesc: "Шүүлтүүр эсвэл хайлтын утгаа өөрчлөн дахин оролдоно уу.",
        bookNow: "Захиалах",
        perHour: "₮ / цаг",
        perHourShort: "/ цаг",
        reviews: "Сэтгэгдэл",
        writeReview: "Сэтгэгдэл бичих",
        postReview: "Нийтлэх",
        shareExperience: "Та сэтгэгдлээ хуваалцана уу...",
        rating: "Үнэлгээ",
        date: "Огноо",
        time: "Цаг",
        duration: "Үргэлжлэх цаг",
        noAvailableSlots: "Боломжит цаг алга байна.",
        total: "Нийт",
        proceedPayment: "Төлбөр төлөх",
        confirmPayment: "Төлбөр баталгаажуулах",
        transferInstruction: "Та доорх данс руу шилжүүлнэ үү",
        bankName: "Банк: Хаан Банк",
        accountName: "Хүлээн авагч: UB Karaoke LLC",
        accountNumber: "Данс: 5000000000",
        clickConfirm: "Шилжүүлсний дараа баталгаажуулах товчийг дарна уу.",
        back: "Буцах",
        confirmTransfer: "Баталгаажуулах",
        bookingConfirmed: "Захиалга баталгаажлаа!",
        reservedMessage: "Таны {venue} дахь захиалга амжилттай.",
        done: "Болсон",
        unknownDistance: "Тодорхойгүй",
        away: "зайтай",
        selectRoom: "Өрөө сонгох",
        capacity: "Хүн",
        features: "Онцлог",
        from: "Эхлэх үнэ",
        tapToReveal: "Харуулах",
        getDirections: "Замын Зааварчилгаа",
        photos: "Зураг",
        close: "Хаах",
        noPhotos: "Зураг байхгүй байна",
        deselectRoom: "Сонголт цуцлах",
        // Districts
        district_Sukhbaatar: "Сүхбаатар",
        district_Chingeltei: "Чингэлтэй",
        district_Bayangol: "Баянгол",
        district_Bayanzurkh: "Баянзүрх",
        district_Songinokhairkhan: "Сонгинохайрхан",
        district_KhanUul: "Хан-Уул",
        district_Nalaikh: "Налайх",
        district_Bagakhangai: "Багахангай",
        district_Baganuur: "Багануур",
        // New keys
        searchByDistrict: "Дүүргээр хайх",
        roomImage: "Өрөөний зураг",
        selectStartTime: "Эхлэх цагаа сонгоно уу",
        venueClosed: "Энэ цагт хаалттай байна",
        workingHours: "Цагийн хуваарь",
        openNow: "ОДОО НЭЭЛТТЭЙ",
        reviewsCount: "Үнэлгээ",
        fullSchedule: "Долоо хоногийн хуваарь",
        // Specs & Features
        microphones: "Микрофон",
        speaker: "Хөгжим",
        screen: "Дэлгэц",
        seating: "Суудал",
        ac: "Эйр кондишн",
        sound: "Тусгаарлалт",
        lighting: "Гэрэлтүүлэг",
        cleaning: "Цэвэрлэгээ",
        view360: "360° Зураг",
        partySupport: "Парти боломжтой",
        birthdaySetup: "Төрсөн өдөр",
        partyDecoration: "Баярын чимэглэл",
        addOns: "Нэмэлт үйлчилгээ",
        inches: "\"",
        mins: "минут",
        // Filter keys
        filterPartyCapable: "🎉 Парти хийх",
        filterCapacity: "Хүний тоо",
        people: "Хүн",
        // Admin Keys
        dashboard: "Хяналтын самбар",
        venuesAndRooms: "Салбар & Өрөө",
        staffUsers: "Ажилчид",
        reports: "Тайлан",
        finance: "Санхүү",
        settings: "Тохиргоо",
        logout: "Гарах",
        viewPublicSite: "Вэбсайт руу очих",
        loggedInAs: "Нэвтэрсэн:",
        venueManagement: "Салбар Удирдлага",
        addBranch: "+ Салбар нэмэх",
        closeBranch: "Хаах",
        reOpen: "Нээх",
        manageRooms: "Өрөө удирдах",
        rooms: "Өрөө",
        closed: "(Хаалттай)",
        actions: "Үйлдэл",
        addRoom: "Өрөө нэмэх",
        roomName: "Өрөөний нэр",
        pricePerHour: "Цагийн үнэ",
        save: "Хадгалах",
        delete: "Устгах",
        areYouSure: "Та итгэлтэй байна уу?",
        // Admin Navigation
        organizations: "Байгууллагууд",
        plans: "Багцууд",
        branchesAndRooms: "Салбар & Өрөө",
        bookings: "Захиалгууд",
        subscription: "Багц",
        pointOfSale: "Касс",
        users: "Хэрэглэгчид",
        staffs: "Ажилчид",
        auditLogs: "Аудит бүртгэл",
        endSession: "Гарах",
        publicSite: "ВЭБ САЙТ",
        managementContext: "Удирдлагын контекст",
        filteringDataText: "Сонгосон салбараар өгөгдлийг шүүх",
        switchOrg: "Байгууллага:",
        switchVenue: "Салбар солих:",
        allOrganizations: "Бүх Байгууллага",
        selectBranchContext: "Салбар сонгох",
        bookingsManagement: "Захиалга удирдах",
        manageBookingsDesc: "Захиалгуудыг удирдах, баталгаажуулах",
        totalBookings: "Нийт захиалга",
        customer: "Захиалагч",
        venueRoom: "Салбар / Өрөө",
        status: "Төлөв",
        approve: "Зөвшөөрөх",
        reject: "Татгалзах",
        bookingDetails: "Захиалгын дэлгэрэнгүй",
        customerContact: "Холбоо барих",
        startTime: "Эхлэх цаг",
        endTime: "Дуусах цаг",
        totalPrice: "Нийт үнэ",
        source: "Эх сурвалж",
        notes: "Тэмдэглэл",
        noContact: "Холбоо байхгүй",
        noContactInfo: "Холбоо барих мэдээлэл байхгүй",
        noBookingsFound: "Захиалга олдсонгүй.",
        filterByVenue: "Салбараар шүүх",
        filterByStatus: "Төлөвөөр шүүх",
        allVenues: "Бүх Салбар",
        allStatuses: "Бүх Төлөв",
        pending: "Хүлээгдэж буй",
        reserved: "Захиалсан",
        confirmed: "Баталгаажсан",
        checkedIn: "Ирсэн",
        completed: "Дууссан",
        cancelled: "Цуцалсан",
        search: "Хайх...",
        reservationNotes: "Захиалгын тэмдэглэл (Заавал биш)",
        notesPlaceholder: "Захиалгын талаарх тэмдэглэл эсвэл холбоо барих нэмэлт утас/и-мэйл хаягаа энд бичнэ үү...",
        // Login Modal
        customerLogin: "Нэвтрэх",
        createAccount: "Бүртгэл үүсгэх",
        adminLoginError: "Ажилчид Админ хуудсаар нэвтэрнэ үү.",
        invalidCredentials: "Нэр эсвэл нууц үг буруу байна.",
        allFieldsRequired: "Бүх талбарыг бөглөнө үү.",
        email: "И-мэйл",
        phone: "Утас",
        emailPlaceholder: "И-мэйл хаяг",
        phonePlaceholder: "Утасны дугаар",
        loginPlaceholder: "И-мэйл/Утас",
        passwordPlaceholder: "Нууц үг",
        noAccount: "Бүртгэлгүй юу? ",
        hasAccount: "Бүртгэлтэй юу? ",
        // Multi-room booking
        bookingDetails: "Захиалгын дэлгэрэнгүй",
        roomsSelected: "Өрөө сонгогдсон",
        confirmSelection: "Сонголтыг баталгаажуулах",
        confirm: "Баталгаажуулах",
        cancel: "Цуцлах",
        onlineBookingDisabled: "Онлайн захиалга түр хаагдсан",
        viewDetails: "Дэлгэрэнгүй харах",
        bookingClosedMessage: "Энэ салбарын онлайн захиалга түр хаагдсан байна. Та холбоо барьж тодруулна уу.",
        // Public Pages
        pricingTitle: "Ил тод үнийн санал",
        pricingSubtitle: "Орчин үеийн караоке бизнест зориулсан хүчирхэг хэрэгсэл. Та өөрийн хэрэгцээнд тохирсон багцыг сонгоорой.",
        mostPopular: "Эрэлттэй",
        contactSales: "Борлуулалттай холбоо барих",
        getStarted: "Эхлэх",
        month: "/сар",
        commission: "Шимтгэл",
        branches: "Салбар",
        unlimitedBranches: "Хязгааргүй Салбар",
        upToRooms: "{count} хүртэл өрөө",
        unlimitedRooms: "Хязгааргүй Өрөө",
        bestFor: "{target}-д тохиромжтой",
        digitalBooking: "24/7 Онлайн Захиалга",

        aboutTitle: "Монголын Шөнийн Амьдралд Хувьсгал Хийж Байна",
        aboutSubtitle: "Бид Улаанбаатар хотын энтертайнмент салбарын дижитал дэд бүтцийг бүтээн байгуулж байна.",
        ourMission: "Бидний Эрхэм Зорилго",
        missionText1: "UB Karaoke нь захиалгын үйл явцыг дижитал хэлбэрт шилжүүлэх ганц зорилготойгоор 2024 онд үүсгэн байгуулагдсан. Бид дуулах дуртай хүмүүсийг хотын шилдэг газруудтай холбодог.",
        missionText2: "Газрын эздэд бид өрөөний ашиглалтыг нэмэгдүүлэх, орлогоо хянах, хэрэглэгчдэд орчин үеийн үйлчилгээ үзүүлэх боломжийг олгодог.",
        communityFirst: "Олон Нийт Нэгт",
        communityDesc: "Дуу хөгжим, хамтын туршлагаар хүмүүсийг холбох.",
        innovation: "Инноваци",
        innovationDesc: "Захиалгын платформ ямар байж болох хязгаарыг тэлэх.",
        reliability: "Найдвартай Байдал",
        reliabilityDesc: "Улаанбаатарын хамгийн том караоке сүлжээнүүдийн итгэлийг хүлээсэн.",
        getInTouch: "Холбоо Барих",

        policyTitle: "Үйлчилгээний Нөхцөл & Нууцлал",
        acceptanceTerms: "Нөхцөл Зөвшөөрөх",
        acceptanceText: "UB Karaoke-г ашигласнаар та энэхүү үйлчилгээний нөхцөлийг зөвшөөрч байна. Бид нөхцөлийг урьдчилан мэдэгдэлгүйгээр өөрчлөх эрхтэй.",
        bookingCancellation: "Захиалга & Цуцлах",
        cancellationPolicy: "Төлбөр төлөгдсөнөөр захиалга баталгаажна. Эхлэхээс дор хаяж 2 цагийн өмнө цуцалбал төлбөрийг бүрэн буцаана. Хоцорч цуцалбал 50% хүртэлх шимтгэл суутгаж болно.",
        dataPrivacy: "Нууцлал",
        privacyText: "Бид таны хувийн мэдээллийг хүндэтгэнэ. Бид зөвхөн захиалга удирдах зорилгоор нэр, утас, и-мэйл цуглуулдаг. Таны мэдээллийг бусдад дамжуулахгүй.",
        codeOfConduct: "Ёс Зүйн Дүрэм",
        conductText: "Хэрэглэгч байгууллагын эд хөрөнгөд хүндэтгэлтэй хандах үүрэгтэй. Тоног төхөөрөмж (микрофон, дэлгэц г.м) эвдсэн тохиолдолд төлбөрийг хэрэглэгч хариуцна.",
        lastUpdated: "Сүүлд шинэчилсэн: 2026 оны 1 сар",
        iAgreeTo: "Би ",
        termsOfService: "Үйлчилгээний Нөхцөл",
        privacyPolicy: "Нууцлалын Бодлого",
        and: " болон ",

        faqTitle: "Түгээмэл Асуултууд",
        faqSubtitle: "UB Karaoke-ийн талаар таны мэдэх ёстой бүх зүйл.",
        faq1_q: "Би яаж өрөө захиалах вэ?",
        faq1_a: "Нүүр хуудаснаас өөрт тохирох газраа сонгоод, өрөө, цагаа сонгон захиалгаа баталгаажуулна уу.",
        faq2_q: "Захиалгаа цуцалж болох уу?",
        faq2_a: "Тийм ээ, 'Миний захиалгууд' хэсгээс цуцлах боломжтой. 2 цагийн өмнө цуцалбал төлбөр суутгахгүй.",
        faq3_q: "Би караоке газраа яаж бүртгүүлэх вэ?",
        faq3_a: "'Үнийн санал' хуудас руу орж тохирох багцыг сонгон бүртгүүлнэ үү. Бид 24 цагийн дотор холбогдох болно.",
        faq4_q: "Төлбөр төлөхөд аюулгүй юу?",
        faq4_a: "Тийм ээ, бид QPay, SocialPay зэрэг найдвартай төлбөрийн системүүдийг ашигладаг.",
        faq5_q: "Хөнгөлөлт байдаг уу?",
        faq5_a: "Газар тус бүр өөрийн урамшуулалтай байж болно. 'Онцгой санал' тэмдэглэгээг хараарай.",
        // Manager Dashboard
        organizationOverview: "Байгууллагын тойм",
        aggregatedStats: "Нэгтгэсэн статистик:",
        liveStatus: "Шууд төлөв",
        organizationName: "Байгууллага",
        orgCode: "Байгууллагын код",
        active: "Идэвхтэй",
        inactive: "Идэвхгүй",
        plan: "Багц",
        totalBookings: "Захиалгууд",
        awaitingApproval: "хүлээгдэж буй",
        branchRevenue: "Салбарын орлого",
        activeBranches: "Идэвхтэй салбарууд",
        quickActions: "Менежерийн түргэн үйлдлүүд",
        manualReservation: "Гараар захиалга хийх",
        performanceReport: "Гүйцэтгэлийн тайлан",
        viewBranchStaff: "Ажилтнуудыг харах",
        manageBookings: "Захиалга удирдах",
        editOrgSettings: "Байгууллагын тохиргоо",
        description: "Тайлбар",
        address: "Хаяг",
        saveChanges: "Хадгалах",
        saving: "Хадгалж байна...",
        assignedBySysadmin: "Системийн админ оноосон",
        orgDescPlaceholder: "Байгууллагын товч тайлбар...",
        addressPlaceholder: "Байгууллагын хаяг...",
        // QPay Payment
        creatingInvoice: "QPay нэхэмжлэх үүсгэж байна...",
        amountToPay: "Төлөх дүн",
        scanQrCode: "Банкны аппликейшнээрээ QR кодыг уншуулна уу",
        orOpenBank: "Эсвэл банкны аппаа шууд нээх",
        waitingForPayment: "Төлбөр баталгаажихыг хүлээж байна...",
        retry: "Дахин оролдох",
        paymentSuccess: "Төлбөр амжилттай!",
        // Cancel Booking
        cancelBookingHeader: "Захиалга цуцлах",
        cancelBookingMessage: "Та энэ захиалгыг цуцлахдаа итгэлтэй байна уу? Цуцлалтын шимтгэл нэхэмжлэгдэх болно.",
        yesCancel: "Тийм, Цуцлах",
        goBack: "Буцах",
        // Booking Errors
        reservationExpired: "Захиалгын хугацаа дууссан. Дахин оролдоно уу.",
        bookingFailed: "Захиалга амжилтгүй боллоо. Дахин оролдоно уу.",
        roomAlreadyBooked: "Энэ өрөө сонгосон цагт аль хэдийн захиалагдсан байна.",
        processing: "Боловсруулж байна...",
        staffBookingRestriction: "Ажилтнууд Админ хуудсаар захиалга хийнэ үү.",
        // Banner & Timer
        actionRequired: "Төлбөр төлнө үү: Захиалга дуусгах",
        completePaymentNow: "Төлбөр төлөх",
        holdRoomMessage: "Таны өрөөг түр хадгаллаа. Захиалга цуцлагдахаас өмнө шилжүүлэг хийнэ үү.",
        dismissBanner: "Хаах",
        expiresIn: "Төлбөр төлж дуусах хугацаа",
        hurryMessage: "Яараарай! Өрөөгөө баталгаажуулахын тулд төлбөрөө төлнө үү.",
        // Profile Page
        memberSince: "{year} оноос хойш гишүүн",
        pts: "ОНОО",
        rewards: "Урамшуулал",
        noUpcomingBookings: "Захиалга байхгүй байна",
        roomSelection: "Өрөө сонголт",
        history: "Түүх",
        hours: "Цаг",
        payNow: "ТӨЛӨХ",
        timeRemaining: "Үлдсэн хугацаа",
        noBookingHistory: "Түүх байхгүй байна",
        goldTier: "Алтан гишүүн",
        currentBalance: "Одоогийн үлдэгдэл",
        pointsToNextTier: "Дараагийн зэрэглэл хүртэл {points} оноо",
        editProfile: "Профайл засах",
        fullName: "Бүтэн нэр",
        phoneNumber: "Утасны дугаар",
        pleaseLogin: "Нэвтэрнэ үү.",
        backToHome: "Нүүр хуудас руу буцах",
        email: "Имэйл хаяг",
        profileUpdatedSuccess: "Профайл амжилттай шинэчлэгдлээ!",
        profileUpdateFailed: "Профайл шинэчлэхэд алдаа гарлаа: "
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('mn'); // Default to Mongolian

    const t = (key, params = {}) => {
        let text = dictionaries[language][key] || key;
        Object.keys(params).forEach(param => {
            text = text.replace(`{${param}}`, params[param]);
        });
        return text;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'en' ? 'mn' : 'en');
    };

    return (
        <LanguageContext.Provider value={{ language, t, toggleLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};
