import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const dictionaries = {
    en: {
        appTitle: "UB KARAOKE",
        home: "Home",
        profile: "Profile",
        aboutUs: "About Us",
        faq: "FAQ",
        policy: "Policy",
        myBookings: "My Bookings",
        searchPlaceholder: "Search karaoke...",
        allDistricts: "All Districts",
        anyRating: "Any Rating",
        stars3: "3+ Stars",
        stars4: "4+ Stars",
        stars45: "4.5+ Stars",
        nearMe: "📍 Near Me",
        noVenues: "No places found matching your search.",
        noVenuesDesc: "Try adjusting your filters or search terms to find more results.",
        bookNow: "Book Now",
        perHour: "₮ / hour",
        perHourShort: "/ hour",
        reviews: "Reviews",
        writeReview: "Write a Review",
        postReview: "Post Review",
        shareExperience: "Share your experience...",
        rating: "Rating",
        date: "Date",
        time: "Time",
        duration: "Duration",
        total: "Total",
        proceedPayment: "Proceed to Payment",
        confirmPayment: "Confirm Payment",
        transferInstruction: "Please transfer",
        bankName: "Bank Name",
        accountName: "Name: UB Karaoke LLC",
        accountNumber: "Account Number",
        clickConfirm: "Click confirm once transferred.",
        back: "Back",
        confirmTransfer: "Confirm Transfer",
        bookingConfirmed: "Booking Confirmed!",
        reservedMessage: "Your room at {venue} is reserved.",
        done: "Done",
        unknownDistance: "Unknown",
        away: "away",
        selectRoom: "Select Room",
        capacity: "People",
        features: "Features",
        from: "From",
        tapToReveal: "Tap to reveal",
        getDirections: "Get Directions",
        photos: "Photos",
        close: "Close",
        noPhotos: "No photos available",
        deselectRoom: "Deselect",
        district_Sukhbaatar: "Sukhbaatar",
        district_Chingeltei: "Chingeltei",
        district_Bayangol: "Bayangol",
        district_Bayanzurkh: "Bayanzurkh",
        district_Songinokhairkhan: "Songinokhairkhan",
        district_KhanUul: "Khan-Uul",
        district_Nalaikh: "Nalaikh",
        district_Bagakhangai: "Bagakhangai",
        district_Baganuur: "Baganuur",
        searchByDistrict: "Search by District",
        roomImage: "Room Image",
        selectStartTime: "Select Start Time",
        venueClosed: "Venue is closed at this time",
        workingHours: "Working Hours",
        openNow: "OPEN NOW",
        reviewsCount: "Reviews",
        fullSchedule: "Full Weekly Schedule",
        microphones: "Microphones",
        speaker: "Speaker Quality",
        screen: "Screen Size",
        seating: "Seating",
        ac: "AC Control",
        sound: "Soundproofing",
        lighting: "Lighting",
        cleaning: "Cleaning",
        view360: "360° View",
        partySupport: "Party Support",
        birthdaySetup: "Birthday Setup",
        partyDecoration: "Party Decoration",
        addOns: "Event Add-ons",
        inches: "\"",
        mins: "mins",
        filterPartyCapable: "🎉 Party Capable",
        filterCapacity: "Capacity",
        people: "People",
        dashboard: "Dashboard",
        venuesAndRooms: "Venues & Rooms",
        staffUsers: "Staff Users",
        reports: "Reports",
        finance: "Finance",
        settings: "Settings",
        viewPublicSite: "View Public Site",
        loggedInAs: "Logged in as:",
        venueManagement: "Branch Management",
        addBranch: "Add Branch",
        closeBranch: "Close Branch",
        reOpen: "Re-open",
        manageRooms: "Manage Rooms",
        rooms: "Rooms",
        closed: "(Closed)",
        closedTakingBookings: "CLOSED (Taking bookings)",
        actions: "Action",
        addRoom: "Add Room",
        roomName: "Room Name",
        pricePerHour: "Price Per Hour",
        save: "Save",
        delete: "Del",
        areYouSure: "Are you sure?",
        organizations: "Organizations",
        plans: "Plans",
        branchesAndRooms: "Branches & Rooms",
        bookings: "Bookings",
        subscription: "Subscription",
        pointOfSale: "Point of Sale (POS)",
        users: "Users",
        staffs: "Staffs",
        auditLogs: "Audit Logs",
        endSession: "End Session",
        publicSite: "View Public Site",
        managementContext: "Management Context",
        filteringDataText: "Filtering data by organization and branch",
        switchOrg: "Org:",
        switchVenue: "Switch venue:",
        allOrganizations: "All Organizations",
        selectBranchContext: "Select a branch from the menu to manage its rooms.",
        bookingsManagement: "Bookings Management",
        manageBookingsDesc: "Manage and approve customer bookings for your venues",
        totalBookings: "Total Bookings",
        customer: "Customer",
        venueRoom: "Venue / Room",
        status: "Status",
        approve: "Approve",
        reject: "Reject",
        bookingDetails: "Booking Details",
        customerContact: "Customer Contact",
        startTime: "Start Time",
        endTime: "End Time",
        totalPrice: "Total Price",
        source: "Source",
        notes: "Notes",
        noContact: "No contact",
        noContactInfo: "No contact information available",
        noBookingsFound: "No bookings found",
        noDataAvailable: "No data available",
        noStaffFound: "No staff found",
        filterByVenue: "Filter by Venue",
        filterByStatus: "Filter by Status",
        allVenues: "All Venues",
        allStatuses: "All Statuses",
        pending: "Pending",
        reserved: "Reserved",
        confirmed: "Confirmed",
        checkedIn: "Checked In",
        completed: "Completed",
        cancelled: "Cancelled",
        rejected: "Rejected",
        expired: "Expired",
        search: "Search...",
        reservationNotes: "Notes for your reservation (optional)",
        notesPlaceholder: "Leave a comment related to your booking or additional phone/email for contact info...",
        customerLogin: "Customer Login",
        signUp: "Sign Up",
        login: "Login",
        logout: "Log out",
        createAccount: "Create Account",
        adminLoginError: "Use Admin Portal for staff login.",
        invalidCredentials: "Invalid credentials",
        allFieldsRequired: "All fields are required",
        email: "Email",
        phone: "Phone",
        emailPlaceholder: "Email Address",
        phonePlaceholder: "e.g. 9911...",
        loginPlaceholder: "Username, Email, or Phone",
        passwordPlaceholder: "Password",
        noAccount: "Don't have an account? ",
        hasAccount: "Already have an account? ",
        roomsSelected: "Rooms Selected",
        confirmSelection: "Confirm Selection",
        confirm: "Confirm",
        cancel: "Cancel",
        onlineBookingDisabled: "Online booking temporarily unavailable",
        viewDetails: "View Details",
        bookingClosedMessage: "Online booking is currently disabled for this venue. Please contact us for inquiries.",
        pricingTitle: "Transparent Pricing",
        pricingSubtitle: "Powerful tools for modern karaoke businesses. Choose the plan that fits your scale.",
        mostPopular: "Most Popular",
        contactSales: "Contact Sales",
        getStarted: "Get Started",
        month: "/mo",
        commission: "Commission",
        branches: "Branch(es)",
        unlimitedBranches: "Up to {count} Branches",
        upToRooms: "Up to {count} Rooms",
        unlimitedRooms: "Unlimited Rooms",
        bestFor: "Best for {target}",
        digitalBooking: "24/7 Digital Booking",
        aboutTitle: "Revolutionizing Nightlife in Mongolia",
        aboutSubtitle: "We are building the digital infrastructure for Ulaanbaatar's entertainment industry.",
        ourMission: "Our Mission",
        missionText1: "UB Karaoke was founded in 2026 with a singular goal: to digitize the fragmented karaoke booking experience. We connect voice enthusiasts with the city's finest venues through a seamless, premium platform.",
        missionText2: "For venue owners, we provide enterprise-grade management tools to optimize room utilization, track revenue, and wow customers with a modern digital presence.",
        communityFirst: "Community First",
        communityDesc: "Connecting people through music and shared experiences.",
        innovation: "Innovation",
        innovationDesc: "Pushing the boundaries of what a booking platform can be.",
        reliability: "Reliability",
        reliabilityDesc: "Trusted by the biggest karaoke chains in UB.",
        getInTouch: "Get in Touch",
        policyTitle: "Terms & Privacy",
        acceptanceTerms: "Acceptance of Terms",
        acceptanceText: "By accessing and using UB Karaoke, you agree to comply with and be bound by these terms and conditions. We reserve the right to modify these terms at any time without prior notice.",
        bookingCancellation: "Booking & Cancellation",
        refundPolicyTitle: "Cancellation & Refund Policy",
        refundTier1Hours: "Free Cancellation Window (hours)",
        refundTier1HoursDesc: "Cancellations before this window will incur no fees.",
        refundTier2Hours: "Partial Cancellation Window (hours)",
        refundTier2HoursDesc: "Cancellations within this window will incur a partial fee.",
        refundTier2Fee: "Partial Cancellation Penalty (%)",
        refundTier3Fee: "Late Cancellation Penalty (%)",
        cancellationPolicy: "Bookings are confirmed upon receipt of payment or confirmation. Cancellations made at least 24 hours prior to the start time receive a full refund. Cancellations between 4 and 24 hours prior incur a 50% penalty. Late cancellations (less than 4 hours) are non-refundable.",
        dataPrivacy: "Data Privacy",
        privacyText: "We value your privacy. We collect basic user information (Name, Phone, Email) solely for booking management and service improvement. Your data is encrypted and stored securely. We do not sell your personal information to third parties.",
        codeOfConduct: "Code of Conduct",
        conductText: "Users are expected to treat venue staff and property with respect. Damages caused to venue equipment (microphones, screens, furniture) will be charged to the user's account.",
        lastUpdated: "Last updated: January 2026",
        iAgreeTo: "I agree to the",
        termsOfService: "Terms of Service",
        privacyPolicy: "Privacy Policy",
        and: "&",
        faqTitle: "Frequently Asked Questions",
        faqSubtitle: "Everything you need to know about UB Karaoke.",
        faq1_q: "How do I book a room?",
        faq1_a: "Simply browse the available venues on our homepage, select a room that fits your group size and budget, choose your time slot, and confirm the booking. You can filter by district, price, and features.",
        faq2_q: "Can I cancel my booking?",
        faq2_a: "Yes, you can cancel your booking through the 'My Bookings' section in your profile. Cancellations made 24 hours in advance are fully refunded. Cancellations 4-24 hours prior incur a 50% fee. No refunds are given for cancellations within 4 hours.",
        faq3_q: "How do I add my karaoke venue to the platform?",
        faq3_a: "Navigate to the 'Pricing' page and choose a plan (Starter, Growth, or Franchise). Once you sign up, our team will review your application and help you set up your venue within 24 hours.",
        faq4_q: "Is payment secure?",
        faq4_a: "Absolutely. We use industry-standard encryption and trusted payment gateways (QPay, SocialPay) to ensure your transactions are safe. We do not store your credit card details.",
        faq5_q: "Do you offer group discounts?",
        faq5_a: "Discounts are determined by individual venues. Look for 'Special Offer' tags on venue cards or check for venues offering 'Party Packages' in the filters.",
        organizationOverview: "Organization Overview",
        aggregatedStats: "Aggregated performance data for",
        liveStatus: "Live Status",
        organizationName: "Organization Name",
        orgCode: "Org Code",
        active: "Active",
        inactive: "Inactive",
        plan: "Plan",
        awaitingApproval: "awaiting approval",
        branchRevenue: "Branch Revenue",
        activeBranches: "Active Branches",
        quickActions: "Quick Actions",
        manualReservation: "Manual Reservation",
        performanceReport: "Performance Report",
        viewBranchStaff: "View Branch Staff",
        manageBookings: "Manage Bookings",
        editOrgSettings: "Edit Organization Settings",
        description: "Description",
        address: "Address",
        saveChanges: "Save Changes",
        saving: "Saving...",
        assignedBySysadmin: "Assigned by System Admin",
        orgDescPlaceholder: "Brief description of your organization...",
        addressPlaceholder: "Organization address...",
        creatingInvoice: "Creating QPay invoice...",
        amountToPay: "Amount to pay",
        scanQrCode: "Scan QR code with your banking app",
        orOpenBank: "Or open your banking app directly",
        waitingForPayment: "Waiting for payment confirmation...",
        retry: "Retry",
        paymentSuccess: "Payment successful!",
        cancelBookingHeader: "Cancel Booking",
        cancelBookingMessage: "Are you sure you want to cancel this booking? Cancellation fees may apply.",
        yesCancel: "Yes, Cancel",
        goBack: "Go Back",
        reservationExpired: "Reservation expired. Please try again.",
        bookingFailed: "Booking failed. Please try again.",
        roomAlreadyBooked: "This room is already booked for the selected time.",
        processing: "Processing...",
        staffBookingRestriction: "Staff must use Admin Panel for manual bookings.",
        actionRequired: "Action Required: Complete Booking",
        completePaymentNow: "Complete Payment Now",
        holdRoomMessage: "Your room is being held. Please complete transfer to avoid cancellation.",
        dismissBanner: "Dismiss Banner",
        expiresIn: "Expires In",
        hurryMessage: "Hurry! Complete your payment to secure this room.",
        memberSince: "Member since {year}",
        pts: "PTS",
        rewards: "Rewards",
        history: "History",
        noAvailableSlots: "No Available Slots",
        noUpcomingBookings: "No upcoming bookings",
        roomSelection: "Room Selection",
        hours: "Hours",
        payNow: "PAY NOW",
        timeRemaining: "Time Remaining",
        noBookingHistory: "No booking history",
        goldTier: "Gold Tier",
        currentBalance: "Current Balance",
        pointsToNextTier: "{points} points to next tier",
        editProfile: "Edit Profile",
        fullName: "Full Name",
        phoneNumber: "Phone Number",
        pleaseLogin: "Please log in.",
        backToHome: "Back to Home",
        profileUpdatedSuccess: "Profile updated successfully!",
        profileUpdateFailed: "Failed to update profile: ",
        roomDashboard: "Room Dashboard",
        viewing: "Viewing",
        signOut: "Sign Out",
        noActiveSession: "No active session",
        tapToFinishCleaning: "Tap to finish cleaning",
        roomControl: "Room Control",
        schedule: "Schedule",
        currentStatus: "Current Status",
        totalBill: "Total Bill",
        noActiveBookingFound: "No Active Booking Found",
        createManualWalkin: "Create Manual Walk-in",
        checkInGuest: "CHECK-IN GUEST",
        completeCheckOut: "COMPLETE & CHECK-OUT",
        posQuickServices: "Point of Sale (Quick Services)",
        addOneHour: "+ 1 Hour",
        extraMic: "Extra Mic",
        popularItems: "Popular Items",
        checkInToEnablePOS: "Check-in guest to enable POS services.",
        yesterday: "Yesterday",
        today: "Today",
        tomorrow: "Tomorrow",
        week: "Week",
        monthLabel: "Month",
        newWalkinReservation: "New Walk-in Reservation",
        guestNameOptional: "Guest Name (Optional)",
        phoneOptional: "Phone (Optional)",
        createReservation: "Create Reservation",
        walkInGuest: "Walk-in Guest",
        missingInfo: "Missing Info",
        fillStartTime: "Please fill in start time.",
        itemAdded: "Item Added",
        addedToOrder: "added to order.",
        extended: "Extended",
        bookingExtended: "Booking extended by 1 hour.",
        staffPortalTitle: "STAFF PORTAL",
        orgCodeLabel: "Organization Code",
        employeeIdLabel: "Employee ID",
        loginButton: "Login",
        loading: "Loading...",
        invalidStaffCredentials: "Invalid organization code or employee ID.",
        orgNotFound: "Organization not found.",
        deviceConfig: "Device Configuration",
        staffLoginWelcome: "Branch credentials required",
        orgSetupHelp: "Configure this device for your organization.",
        accessDeniedStaff: "Access Denied: Only staff and managers can access this portal.",
        oneTimeSetup: "One-Time Setup",
        orgCodeSetupDesc: "Enter your Organization Code here. Access to this device will be restricted to this organization.",
        deviceConfigSuccess: "Device configured successfully",
        configCleared: "Configuration cleared",
        clickToSetupOrg: "Click to setup org code",
        deviceNotConfigured: "Device not configured",
        configuredFor: "Configured for",
        secureLogin: "Secure Login",
        username: "Username",
        passwordPin: "Password / PIN",
        id: "ID",
        selectVenue: "Select Venue",
        createAndConfirm: "Create & Confirm",
        newManualBooking: "New Manual Booking",
        bookingCreatedSuccess: "Booking Created & Confirmed!",
        bookingCreateFailed: "Failed to create booking. Check availability.",
        approveBookingConfirm: "Approve this booking?",
        rejectBookingConfirm: "Reject this booking?",
        auditLogsDesc: "Historical record of system activities and changes",
        refreshStream: "Refresh Stream",
        filterByEvent: "Filter by Event",
        filterByStaff: "Filter by Staff",
        allEvents: "All Events",
        allStaff: "All Staff",
        timestamp: "Timestamp",
        activity: "Activity",
        actor: "Actor",
        targetEntity: "Target Entity",
        eventMetadata: "Event Metadata",
        pointsLabel: "Points",
        globalOverview: "Global Overview",
        aggregatedDiagnostics: "Aggregated diagnostics for across",
        organizationsLabel: "organizations",
        networkStatus: "Network Status",
        operational: "Operational",
        healthyOperational: "Healthy & Operational",
        globalOrganizations: "Global Organizations",
        activeEntities: "Active Entities",
        platformRevenue: "Platform Revenue",
        totalRegisteredUsers: "Total Registered Users",
        pendingInquiries: "Pending Inquiries",
        systemAdministration: "System Administration",
        financialCSV: "Financial CSV",
        platformSettings: "Platform Settings",
        globalCommission: "Global Commission",
        taxCompliance: "Tax Compliance",
        settingsSaved: "Settings Saved",
        settingsSavedDetail: "System configuration updated successfully",
        validationError: "Validation Error",
        fillAllFields: "Please fill all fields",
        promoAdded: "Promotion Added",
        promoCodeCreated: "Code {code} created",
        promoAddFailed: "Failed to add promotion",
        promoDeleted: "Promotion Deleted",
        promoRemoved: "Code removed",
        systemSettings: "System Settings",
        systemSettingsDesc: "Configure global platform parameters and promotional offers",
        financialConfig: "Financial Configuration",
        vatRate: "VAT Tax Rate",
        multiplierSuffix: " (Multiplier)",
        vatExample: "Example: 0.10 for 10% VAT",
        serviceCharge: "Service Charge",
        chargeExample: "Example: 0.05 for 5% charge",
        currencySymbol: "Currency Symbol",
        saveFinancialSettings: "Save Financial Settings",
        activePromoCodes: "Active Promo Codes",
        addNew: "Add New",
        noActivePromos: "No active promotions currently configured.",
        off: "OFF",
        validRange: "Valid: {start} - {end}",
        addNewPromoCode: "Add New Promo Code",
        promoCodeLabel: "PROMO CODE",
        type: "Type",
        percentage: "Percentage (%)",
        fixedAmount: "Fixed Amount (₮)",
        value: "Value",
        startDate: "Start Date",
        endDate: "End Date",
        createPromotion: "Create Promotion",
        reportsAnalytics: "Reports & Analytics",
        reportsAnalyticsDesc: "Business performance and operation insights",
        daily: "Daily",
        monthly: "Monthly",
        exportPdf: "Export PDF",
        exportReport: "Export Monthly Report",
        selectMonthToExport: "Select Month",
        downloadExcel: "Download Excel (.xlsx)",
        downloadPdf: "Download PDF (.pdf)",
        revenueTrend: "Revenue Trend (Last 7 Days)",
        topOperatingRooms: "Top Operating Rooms",
        totalBookingsStat: "{count} Total Bookings",
        repPerformance: "Representative Performance",
        bookingsAssistedStat: "{count} Bookings Assisted",
        mvp: "MVP",
        unknownRoom: "Unknown Room",
        financeSettlement: "Finance & Settlement",
        financeSettlementDesc: "Manage earnings, payouts and bank accounts",
        addBankAccount: "Add Bank Account",
        totalNetEarnings: "Total Net Earnings",
        availableForPayout: "Available for Payout",
        totalPaidOut: "Total Paid Out",
        earningsTab: "Earnings",
        payoutsTab: "Payouts",
        bankAccountsTab: "Bank Accounts",
        gross: "Gross",
        comm: "Comm.",
        net: "Net",
        bankAccount: "Bank Account",
        owner: "Owner",
        requestPayoutItems: "{count} items selected",
        selectBankAccount: "Select Bank Account",
        selectAccountLabel: "Select account",
        submitRequest: "Submit Request",
        accountHolderName: "Account Holder Name",
        bankPlaceholder: "e.g. Khan Bank",
        holderPlaceholder: "Enter name",
        numberPlaceholder: "Enter account number",
        setAsDefaultPayout: "Set as default payout account",
        pendingPayouts: "Pending Payout Requests",
        managePayouts: "Manage Payouts",
        payoutManagement: "Payout Management",
        manualPayout: "Manual Payout Request",
        manualPayoutDesc: "Create a payout request for an organization manually.",
        payoutLimit: "Minimum Payout Limit",
        payoutLimitDesc: "Minimum amount required for an organization to request a payout.",
        notificationConfig: "Notification Configuration",
        adminEmailRecipients: "Admin Email Recipients",
        adminEmailsDesc: "Comma-separated emails to receive platform alerts (e.g. payout requests).",
        adminEmailsInfo: "If left empty, payout notifications will be sent to all users with the 'System Admin' role.",
        selectionRequired: "Selection Required",
        payoutItemsSelection: "Please select earnings to payout",
        addPayoutAccountFirst: "Please add a payout account first",
        saveSystemSettings: "Save System Settings",
        payoutRequestedSuccess: "Payout requested successfully",
        payoutRequestFailed: "Failed to request payout",
        payoutAccountAdded: "Payout account added",
        payoutAccountAddFailed: "Failed to add bank account",
        payoutMarkedAs: "Payout marked as {status}",
        unknownVenue: "Unknown Venue",
        plansLabel: "Plans",
        orgsLabel: "Organizations",
        systemAdminTitle: "SYSTEM ADMIN",
        platformControl: "UB Karaoke Platform Control",
        accessDeniedSysadminOnly: "Access Denied. System Administrators only.",
        returnToPublic: "Return to PUBLIC WEBSITE",
        loggingIn: "Logging in...",
        customerCreated: "Customer Created",
        customerCreatedDetail: "New customer added successfully",
        customerCreateFailed: "Failed to create customer",
        customerStatusDetail: "Customer {status} successfully",
        customerManagement: "Customer Management",
        customerManagementDesc: "Manage registered customers and their accounts",
        addCustomer: "Add Customer",
        points: "Points",
        noCustomersFoundLabel: "No customers found",
        addNewCustomer: "Add New Customer",
        enterFullName: "Enter full name",
        enterUsername: "Enter username",
        enterEmail: "Enter email",
        enterPhone: "Enter phone",
        enterPassword: "Enter password",
        createCustomer: "Create Customer",
        newPasswordLabel: "New Password",
        staffCreated: "Staff Created",
        staffCreatedDetail: "New staff member added successfully",
        staffCreateFailed: "Failed to create staff",
        staffUpdated: "Staff Updated",
        staffUpdatedDetail: "Staff member updated successfully",
        staffUpdateFailed: "Failed to update staff",
        branchManager: "Branch Manager",
        staffMember: "Staff Member",
        systemAdmin: "System Admin",
        global: "Global",
        staffStatusDetail: "Staff member {status} successfully",
        staffManagement: "Staff Management",
        manageUsersRoles: "Manage users and roles across your organization",
        filterByOrganization: "Filter by Organization",
        addStaff: "Add Staff",
        noStaffFoundLabel: "No staff found",
        addNewStaffMember: "Add New Staff Member",
        selectRoleLabel: "Select Role",
        selectOrganization: "Select Organization",
        createStaff: "Create Staff",
        editStaffMember: "Edit Staff Member",
        resetPasswordFor: "Reset Password for {name}",
        venueDescriptionPlaceholder: "Premium karaoke experience in Ulaanbaatar.",
        venuePhonePlaceholder: "+976 99000000",
        editType: "Edit Type",
        addType: "Add Type",
        editFeature: "Edit Feature",
        addFeature: "Add Feature",
        roomSingular: "Room",
        durationHours: "Duration (h)",
        bookingId: "Booking ID",
        noPaymentsFound: "No payments found",
        method: "Method",
        redirectingToHome: "Redirecting to home...",
        organizationUpdated: "Organization information has been updated.",
        organizationCreated: "New organization has been registered.",
        failedToSaveOrganization: "Failed to save organization details.",
        failedToUploadLogo: "Failed to upload logo image.",
        clickToCopyId: "Click to copy full ID",
        uniqueCode: "Unique Code",
        planStatus: "Plan Status",
        planStart: "Plan Start",
        planEnd: "Plan End",
        viewPlanHistory: "View Plan History",
        currentPlan: "Current Plan",
        editOrganization: "Edit Organization",
        newOrganizationHeader: "Create New Organization",
        internalCodeUnique: "Internal Code (Unique)",
        selectPlan: "Select a Plan",
        planHistoryFor: "Plan History for {name}",
        noHistoryFound: "No history found",
        commissionRateLabel: "Commission Rate",
        planUpdated: "Subscription plan has been updated.",
        planCreated: "New subscription plan has been created.",
        failedToSavePlan: "Failed to save subscription plan.",
        freeCustom: "Free / Custom",
        editPlan: "Edit Plan",
        deletePlan: "Delete Plan",
        subscriptionPlans: "Subscription Plans",
        definePlansDesc: "Define and manage organization subscription tiers",
        createNewPlan: "Create New Plan",
        monthlyFeeLabel: "Monthly Fee",
        modifyPlan: "Modify Subscription Plan",
        establishTier: "Establish New Plan Tier",
        planDisplayName: "Plan Display Name",
        internalUniqueCode: "Internal Unique Code",
        monthlyFeeMNT: "Monthly Fee (MNT)",
        platformCommission: "Platform Commission (%)",
        branchLimit: "Branch Limit",
        roomCountLimit: "Room Count Limit",
        updateTier: "Update Tier",
        createTier: "Create Tier",
        failedToLoadSubscription: "Failed to load subscription data",
        subscriptionUpdatedSuccess: "Subscription updated successfully!",
        paymentFailed: "Payment failed. Please try again.",
        planSubscription: "Plan & Subscription",
        manageSubDesc: "Manage your organization's business tier and billing",
        currentSubscription: "Current Subscription",
        standardFree: "Standard / Free",
        customPricing: "Custom Pricing",
        planQuotas: "Plan Quotas & Features",
        branchCapacity: "Branch Capacity",
        totalVenuesNote: "* Total venues active in the system",
        onlineBookings: "Online Bookings",
        prioritySupport: "Priority Support",
        extendOrUpgrade: "Extend or Upgrade Plan",
        choosePlanDesc: "Choose a plan duration or switch to a higher tier for more features",
        unlimitedLabel: "Unlimited",
        commissionRateDetail: "{rate}% Commission Rate",
        coreFeaturesInclude: "All core management features",
        oneMonth: "1 Month",
        sixMonths: "6 Months",
        securePayment: "Secure Subscription Payment",
        processingPayment: "Processing Payment...",
        commGateway: "Communicating with banking gateway",
        planSelection: "Plan Selection",
        totalAmount: "Total Amount",
        paymentDisclaimer: "BY CLICKING CONFIRM, YOU AUTHORIZE THE MOCK PAYMENT SYSTEM TO EXTEND YOUR SUBSCRIPTION FOR {duration} MONTHS.",
        roomPresentation: "Room Presentation",
        promotionImage: "Promotion Image",
        roomAmenities: "Room Amenities & Features",
        advancedPricing: "Advanced Dynamic Pricing",
        addPricingRule: "Add Pricing Rule",
        pricingType: "Pricing Type",
        happyHourRecurring: "Happy Hour (Recurring)",
        specificDate: "Specific Date",
        applyTo: "Apply to Day Type",
        dateRange: "Date Range",
        specialRatePerHour: "Special Rate / Hr",
        priorityLabel: "Priority (Lower number = higher priority)",
        noPricingRules: "No special pricing rules defined.",
        roomRefPlaceholder: "e.g. VIP Room 301",
        failedToUpdateOrder: "Failed to update room order",
        failedToAddRule: "Failed to add rule",
        failedToRemoveRule: "Failed to remove rule",
        pricingRuleAdded: "Pricing rule added",
        pricingRuleRemoved: "Pricing rule removed",
        holidayEvent: "Holiday / Event",
        recurring: "Recurring",
        everyday: "Everyday",
        weekdays: "Weekdays",
        weekends: "Weekends",
        roomUpdated: "Room updated",
        roomAdded: "Room added",
        venueName: "Venue Name",
        addressPlaceholderDetail: "e.g. 1st Floor, Shangri-La Mall",
        gmapPlaceholder: "e.g. 47.9189, 106.9176",
        customPerDay: "Custom per day",
        dailyAllDays: "Daily (All Days)",
        priceTier: "Price Tier",
        venueBranding: "Venue Branding",
        orLabel: "OR",
        selectStockImage: "Select Stock Image",
        organizationOwner: "Organization Owner",
        updateChanges: "Update Changes",
        createVenue: "Create Venue",
        roomReferenceName: "Room Reference Name",
        selectRoomType: "Select Room Type",
        maxCapacity: "Max Capacity",
        enableOnlineBooking: "Enable Online Booking",
        iconLabel: "Icon (Emoji)",
        paymentHistory: "Payment History",
        refresh: "Refresh",
        amount: "Amount",
        branchRoomsInventory: "Branch Rooms & Inventory",
        room: "Room",
        ratePerHour: "Rate / Hour",
        bookingStatus: "Booking Status",
        deleteConfirmation: "Delete Confirmation",
        roomCategory: "Room Category",
        physicalAddress: "Physical Address",
        phoneContact: "Phone Contact",
        openingHours: "Opening Hours",
        bookingSystemSettings: "Booking System Settings",
        allowedStartTime: "Allowed Start Time",
        allowedEndTime: "Allowed End Time",
        maxAdvanceBooking: "Max Advance Booking (Days)",
        minBooking: "Min Booking (Hours)",
        maxBooking: "Max Booking (Hours)",
        uploadCustomImage: "Upload Custom Image",
        editDetails: "Edit Details",
        deactivateRoom: "Deactivate Room",
        activateRoom: "Activate Room",
        editRoom: "Edit Room",
        deleteRoom: "Delete Room",
        roomSettings: "Room Settings",
        noBranchSelected: "No Branch Selected",
        noRoomsFound: "No rooms found for this branch.",
        selectAmenities: "Select Features",
        seasonalOverride: "Seasonal Overrides & Happy Hours",
        specificDatesOnly: "Specific Dates Only (Holidays)",
        selectDates: "Select dates...",
        dates: "Dates",
        rate: "Rate",
        budget: "Budget",
        standard: "Standard",
        premium: "Premium",
        luxury: "Luxury",
        district: "District",
        selectDistrict: "Select District",
        resetPassword: "Reset Password",
        enterNewPassword: "Enter new password",
        passwordResetSuccess: "Password Reset",
        statusUpdated: "Status Updated",
        organization: "Organization",
        unknown: "Unknown",
        bookingApproved: "Booking approved successfully",
        bookingRejected: "Booking has been rejected",
        roomTypes: "Room Types",
        featuresAmenities: "Features / Amenities",
        promoDeleteFailed: "Failed to delete promotion",
        standardRoom: "Standard Room",
        vipLounge: "VIP Lounge",
        partyHall: "Party Hall",
        minimalSmall: "Minimal/Small",
        bookingOn: "Booking ON",
        bookingOff: "Booking OFF",
        venueUpdatedSuccess: "Venue updated successfully",
        venueAddedSuccess: "Venue added successfully",
        venueRemovedSuccess: "Venue removed successfully",
        venueStatusActive: "Venue marked as active",
        venueStatusInactive: "Venue marked as inactive",
        roomOrderUpdated: "Room order updated",
        gmapLocationLabel: "GMap Location (Lat, Long)",
        priority: "Priority",
        walkinBookingCreated: "Walk-in booking created",
        roomNowOccupied: "{name} is now occupied",
        roomNowCleaning: "{name} is now awaiting cleaning",
        roomNowAvailable: "{name} is now available",
        checkInFailed: "Check-in failed",
        checkOutFailed: "Check-out failed",
        sengurBottle: "Sengur (Bottle)",
        heinekenBottle: "Heineken (Bottle)",
        coke05: "Coca Cola 0.5L",
        water05: "Water 0.5L",
        mixedNuts: "Mixed Nuts",
        fruitPlatter: "Fruit Platter",
        frenchFries: "French Fries",
        drinks: "Drinks",
        snacks: "Snacks",
        food: "Food",
        available: "Available",
        occupied: "Occupied",
        maintenance: "Maintenance",
        noActivePlan: "NO ACTIVE PLAN",
        expiringSoon: "EXPIRING SOON",
        validUntil: "Valid Until",
        planId: "Plan ID",
        proceedToPayment: "Proceed to Payment",
        organizationManagement: "Organization Management",
        manageEntitiesDesc: "Manage business entities and their configurations",
        newOrganization: "New Organization",
        uploadLogo: "Upload Logo",
        planHistory: "Plan History",
        copied: "Copied",
        idCopied: "ID copied to clipboard",
        resume: "Resume",
        pause: "Pause",
        noBookingsFoundMn: "No bookings found",
        itemAddedMn: "Item Added",
        addedToOrderMn: "added to order.",
        unlimited: "Unlimited",
        discard: "Discard",
        // Promotions Management Page
        promotions: "Promotions",
        promotionsPageDesc: "Manage promo codes and track their usage",
        searchPromoCodes: "Search promo codes...",
        activeOnly: "Active Only",
        showingAll: "Showing All",
        filterByPeriod: "Filter by period...",
        createFirstPromo: "Create your first promo code",
        noMatchingPromos: "No matching promo codes",
        timesUsed: "times used",
        upcoming: "Upcoming",
        editPromoCode: "Edit Promo Code",
        editPromoDesc: "Update promotion details",
        addPromoDesc: "Create a new promotional code",
        codeNotEditable: "Promo code cannot be changed after creation",
        venuePromoHint: "Select a venue or 'All Venues' to apply across the organization",
        promoUsageHistory: "Promo Usage History",
        allPromos: "All Promo Codes",
        filterByPromo: "Filter by promo code",
        noPromoBookings: "No bookings have used promo codes yet",
        noResults: "No results found",
        promoCode: "Promo Code",
        discount: "Discount",
        venue: "Venue",
        edit: "Edit",
        error: "Error",
        confirmDelete: "Confirm Delete",
        promoUpdated: "Updated",
        promoCodeUpdated: "Promotion \"{code}\" updated",
        promoUpdateFailed: "Update failed",
        havePromoCode: "Have a promo code?",
        promoApplied: "Promo Applied!",
        removePromo: "Remove",
        enterPromoCode: "Enter code...",
        applyPromo: "Apply",
        promoInvalid: "Invalid promotion code",
        identityAvatar: "Identity & Avatar",
        profileAvatar: "Profile Avatar",
        personalDetails: "Personal Details",
        accessSecurity: "Access & Security",
        contactInformation: "Contact Information",
        roleAssignment: "Role Assignment",
        organizationLink: "Organization Link",
        identityProfile: "Identity & Profile",
        security: "Security",
        onboardingClient: "Onboarding New Client",
        idNumber: "ID Number",
        passwordShort: "PASSWD",
        scheduleAndRoom: "Schedule & Room",
        pricingAndStatus: "Pricing & Status",
        customerNotes: "Customer Notes",
        notProvided: "Not Provided",
        promoIdentity: "Promo Identity",
        rewardCode: "Reward Code",
        discountPolicy: "Discount Policy",
        timeScope: "Time & Scope",
        trackingDetail: "Tracking all successful applications",
        identityBranding: "Identity & Branding",
        contactLocation: "Contact & Location",
        subscriptionPlan: "Subscription & Plan",
        resetPasswordHint: "User will need to login with this new password",
        confirmReset: "Confirm Reset",
        venueIdentity: "Venue Identity",
        locationDetails: "Location Details",
        venueBrandingHeader: "Venue Branding",
        roomIdentity: "Room Identity",
        roomPresentationHeader: "Room Presentation",
        capacityAndPricing: "Capacity & Pricing",
        venueOnboarding: "Venue Onboarding",
        roomOnboarding: "Room Onboarding",
        venueOnboardingDesc: "Configure your branch profile and settings",
        roomOnboardingDesc: "Set up room details, amenities and pricing",
        notifications: "Notifications",
        markAllRead: "Mark all read",
        noNotifications: "No notifications yet",
        viewAll: "View All",
        offline: "Offline",
        receiveNotification: "Receive Notification",

        // Tour Content
        tourNext: "Next",
        tourPrev: "Back",
        tourSkip: "Skip",
        tourClose: "Close",
        tourDoNotShow: "Do not show again",
        tourVenueTitle: "Venue Selection",
        tourVenueContent: "Welcome to the Staff Portal! Start by confirming or selecting the venue you are managing today.",
        tourRoomsTitle: "Room Dashboard",
        tourRoomsContent: "Monitor all room statuses here in real-time. Red means occupied, green is available.",
        tourNotificationTitle: "Booking Alerts",
        tourNotificationContent: "Keep an eye on this bell for new online bookings requiring your approval or payment collection.",
        tourProfileTitle: "Profile Menu",
        tourProfileContent: "Access your profile settings or sign out securely from here.",

        changeTime: "Change Time",
        paymentNotConfirmedYet: "Payment not confirmed yet. Please scan the QR and pay first.",
        imAlreadyPaid: "Check payment",
        reschedule: "Reschedule",
        bookingRescheduled: "Booking Rescheduled!",
        newTime: "New Time",
        currentTime: "Current Time",
        reschedulesLeft: "Reschedules Left",
        chooseDateStep: "1. Choose a Date",
        chooseTimeStep: "2. Choose a Time",
        confirmReschedule: "Confirm Reschedule",
        rescheduling: "Rescheduling...",
        rescheduleInfo: "You can reschedule up to 3 times. Must be at least 1 hour before your current booking start, and 2+ hours from now.",
        noSlotsOnDate: "No available slots on this date.",
        refunds: "Refunds",
        refundManagement: "Refund Management",
        refundsDesc: "Manage customer booking cancellations and refunds",
        totalPendingRefunds: "Total Pending",
        processRefund: "Process Refund",
        refundInitiated: "Refund of",
        refundProcessing: "will be processed within 5-7 business days.",
        refundAmount: "Refund Amount",
        refundFee: "Cancellation Fee",
        payoutRef: "Ref",
        markAsProcessed: "Mark as Processed",
        markAsProcessedConfirm: "Mark this refund as processed?",
        refundProcessedSuccess: "Refund marked as processed",
        refundCancelled: "Booking Cancelled",
        cancellationConfirmed: "Your booking has been cancelled.",
        refundReason: "Reason",
        refundDate: "Date",
        totalRefunded: "Total Refunded",
        completedRefunds: "Completed",
        noRefundsFound: "No refunds found",
        refundDetails: "Refund Details",
        customerCancellationRefunds: "CUSTOMER CANCELLATION REFUNDS",
        bookingRef: "Booking Ref",
        markProcessed: "Mark Processed",

        // Notification Content (Backend mapped)
        "Booking Created": "Booking Created",
        "Slot Reserved": "Slot Reserved",
        "Booking Approved": "Booking Approved",
        "Booking Rejected": "Booking Rejected",
        "Checked In": "Checked In",
        "Booking Completed": "Booking Completed",
        "Reservation Expired": "Reservation Expired",
        "Payment Reminder": "Payment Reminder",
        "New Walk-in Reservation": "New Walk-in Reservation",
        "Payment Received": "Payment Received",
        "Booking Cancelled": "Booking Cancelled",

        "Your booking has been created and is pending approval": "Your booking has been created and is pending approval.",
        "Your time slot has been reserved. Complete payment within 15 minutes.": "Your time slot has been reserved. Complete payment within 15 minutes.",
        "Your booking has been approved!": "Your booking has been approved!",
        "Your booking has been rejected": "Your booking has been rejected.",
        "You have been checked in. Enjoy your session!": "You have been checked in. Enjoy your session!",
        "Your booking is complete. Thank you!": "Your booking is complete. Thank you!",
        "Your booking reservation has expired": "Your booking reservation has expired.",
        "Your reservation expires soon. Complete payment now!": "Your reservation expires soon. Complete payment now!",
        "Manual walk-in booking created": "Manual walk-in booking created.",
        "Customer has been successfully checked in.": "Customer has been successfully checked in."
    },
    mn: {
        appTitle: "UB КАРАОКЕ",
        home: "Нүүр",
        profile: "Профайл",
        aboutUs: "Бидний тухай",
        faq: "Түгээмэл асуултууд",
        policy: "Үйлчилгээний нөхцөл",
        myBookings: "Миний захиалгууд",
        searchPlaceholder: "Караоке хайх...",
        allDistricts: "Бүх дүүрэг",
        anyRating: "Бүх үнэлгээ",
        stars3: "3+ Од",
        stars4: "4+ Од",
        stars45: "4.5+ Од",
        nearMe: "📍 Ойрхон",
        noVenues: "Таны хайлтад тохирох газар олдсонгүй.",
        noVenuesDesc: "Шүүлтүүр эсвэл хайлтын утгаа өөрчлөн дахин оролдоно уу.",
        bookNow: "Захиалах",
        perHour: "₮ / цаг",
        perHourShort: "/ цаг",
        reviews: "Сэтгэгдэл",
        writeReview: "Сэтгэгдэл бичих",
        postReview: "Нийтлэх",
        shareExperience: "Та сэтгэгдлээ хуваалцана уу...",
        rating: "Үнэлгээ",
        date: "Огноо",
        time: "Цаг",
        duration: "Хугацаа",
        total: "Нийт",
        proceedPayment: "Төлбөр төлөх",
        confirmPayment: "Төлбөр баталгаажуулах",
        transferInstruction: "Та доорх данс руу шилжүүлнэ үү",
        bankName: "Банкны нэр",
        accountName: "Хүлээн авагч: UB Karaoke LLC",
        accountNumber: "Дансны дугаар",
        clickConfirm: "Шилжүүлсний дараа баталгаажуулах товчийг дарна уу.",
        back: "Буцах",
        confirmTransfer: "Баталгаажуулах",
        bookingConfirmed: "Захиалга баталгаажлаа!",
        reservedMessage: "Таны {venue} дахь захиалга амжилттай.",
        done: "Болсон",
        unknownDistance: "Тодорхойгүй",
        away: "зайтай",
        selectRoom: "Өрөө сонгох",
        capacity: "Хүн",
        features: "Онцлог",
        from: "Эхлэх үнэ",
        tapToReveal: "Харуулах",
        getDirections: "Замын Зааварчилгаа",
        photos: "Зураг",
        close: "Хаах",
        noPhotos: "Зураг байхгүй байна",
        deselectRoom: "Сонголт цуцлах",
        district_Sukhbaatar: "Сүхбаатар",
        district_Chingeltei: "Чингэлтэй",
        district_Bayangol: "Баянгол",
        district_Bayanzurkh: "Баянзүрх",
        district_Songinokhairkhan: "Сонгинохайрхан",
        district_KhanUul: "Хан-Уул",
        district_Nalaikh: "Налайх",
        district_Bagakhangai: "Багахангай",
        district_Baganuur: "Багануур",
        searchByDistrict: "Дүүргээр хайх",
        roomImage: "Өрөөний зураг",
        selectStartTime: "Эхлэх цагаа сонгоно уу",
        venueClosed: "Энэ цагт хаалттай байна",
        workingHours: "Цагийн хуваарь",
        openNow: "ОДОО НЭЭЛТТЭЙ",
        reviewsCount: "Үнэлгээ",
        fullSchedule: "Долоо хоногийн хуваарь",
        microphones: "Микрофон",
        speaker: "Хөгжим",
        screen: "Дэлгэц",
        seating: "Суудал",
        ac: "Эйр кондишн",
        sound: "Тусгаарлалт",
        lighting: "Гэрэлтүүлэг",
        cleaning: "Цэвэрлэж буй",
        view360: "360° Зураг",
        partySupport: "Парти боломжтой",
        birthdaySetup: "Төрсөн өдөр",
        partyDecoration: "Баярын чимэглэл",
        addOns: "Нэмэлт үйлчилгээ",
        inches: "\"",
        mins: "минут",
        filterPartyCapable: "🎉 Парти хийх",
        filterCapacity: "Хүний тоо",
        people: "Хүн",
        dashboard: "Хяналтын самбар",
        venuesAndRooms: "Салбар ба өрөөнүүд",
        staffUsers: "Ажилчид",
        reports: "Тайлан",
        finance: "Санхүү",
        settings: "Тохиргоо",
        viewPublicSite: "Вэбсайт руу очих",
        loggedInAs: "Нэвтэрсэн:",
        venueManagement: "Салбарын удирдлага",
        addBranch: "Салбар нэмэх",
        closeBranch: "Хаах",
        reOpen: "Нээх",
        manageRooms: "Өрөө удирдах",
        rooms: "Өрөөнүүд",
        closed: "(Хаалттай)",
        closedTakingBookings: "ХААЛТТАЙ (Захиалга авна)",
        actions: "Үйлдэл",
        addRoom: "Өрөө нэмэх",
        roomName: "Өрөөний нэр",
        pricePerHour: "Цагийн үнэ",
        save: "Хадгалах",
        delete: "Устгах",
        areYouSure: "Та итгэлтэй байна уу?",
        organizations: "Байгууллагууд",
        plans: "Багцууд",
        branchesAndRooms: "Салбар ба өрөөнүүд",
        bookings: "Захиалгууд",
        subscription: "Багц",
        pointOfSale: "ПОС систем",
        users: "Хэрэглэгчид",
        staffs: "Ажилчид",
        auditLogs: "Аудит лог",
        endSession: "Системээс гарах",
        publicSite: "Нүүр хуудас",
        managementContext: "Удирдлагын орчин",
        filteringDataText: "Байгууллага болон салбараар өгөгдөл шүүх",
        switchOrg: "Байгууллага:",
        switchVenue: "Салбар солих:",
        allOrganizations: "Бүх байгууллага",
        selectBranchContext: "Салбар сонгох...",
        bookingsManagement: "Захиалга удирдах",
        manageBookingsDesc: "Захиалгуудыг удирдах, баталгаажуулах",
        totalBookings: "Нийт захиалга",
        customer: "Захиалагч",
        venueRoom: "Салбар / Өрөө",
        status: "Төлөв",
        approve: "Зөвшөөрөх",
        reject: "Татгалзах",
        bookingDetails: "Захиалгын дэлгэрэнгүй",
        customerContact: "Хэрэглэгчийн холбоо барих",
        startTime: "Эхлэх цаг",
        endTime: "Дуусах цаг",
        totalPrice: "Нийт үнэ",
        source: "Эх сурвалж",
        notes: "Тэмдэглэл",
        noContact: "Холбоо барих мэдээлэлгүй",
        noContactInfo: "Холбоо барих мэдээлэл байхгүй",
        noBookingsFound: "Захиалга олдсонгүй",
        noDataAvailable: "Өгөгдөл байхгүй байна",
        noStaffFound: "Ажилтан олдсонгүй",
        filterByVenue: "Салбараар шүүх",
        filterByStatus: "Төлөвөөр шүүх",
        allVenues: "Бүх салбар",
        allStatuses: "Бүх Төлөв",
        pending: "Хүлээгдэж буй",
        reserved: "Захиалсан",
        confirmed: "Баталгаажсан",
        checkedIn: "Ирсэн",
        completed: "Дууссан",
        cancelled: "Цуцалсан",
        rejected: "Татгалзсан",
        expired: "Хугацаа дууссан",
        search: "Хайх...",
        reservationNotes: "Захиалгын тэмдэглэл (Заавал биш)",
        notesPlaceholder: "Захиалгын талаарх тэмдэглэл эсвэл холбоо барих нэмэлт утас/и-мэйл хаягаа энд бичнэ үү...",
        customerLogin: "Нэвтрэх",
        signUp: "Бүртгүүлэх",
        login: "Нэвтрэх",
        logout: "Гарах",
        createAccount: "Бүртгэл үүсгэх",
        adminLoginError: "Ажилчид Админ хуудсаар нэвтэрнэ үү.",
        invalidCredentials: "Нэр эсвэл нууц үг буруу байна.",
        allFieldsRequired: "Бүх талбарыг бөглөнө үү.",
        email: "Имэйл хаяг",
        phone: "Утас",
        emailPlaceholder: "И-мэйл хаяг",
        phonePlaceholder: "Жишээ: 9911...",
        loginPlaceholder: "И-мэйл/Утас",
        passwordPlaceholder: "Нууц үг",
        noAccount: "Бүртгэлгүй юу? ",
        hasAccount: "Бүртгэлтэй юу? ",
        roomsSelected: "Өрөө сонгогдсон",
        confirmSelection: "Сонголтыг баталгаажуулах",
        confirm: "Баталгаажуулах",
        cancel: "Цуцлах",
        onlineBookingDisabled: "Онлайн захиалга түр хаагдсан",
        viewDetails: "Дэлгэрэнгүй харах",
        bookingClosedMessage: "Энэ салбарын онлайн захиалга түр хаагдсан байна. Та холбоо барьж тодруулна уу.",
        pricingTitle: "Ил тод үнийн санал",
        pricingSubtitle: "Орчин үеийн караоке бизнест зориулсан хүчирхэг хэрэгсэл. Та өөрийн хэрэгцээнд тохирсон багцыг сонгоорой.",
        mostPopular: "Эрэлттэй",
        contactSales: "Борлуулалттай холбоо барих",
        getStarted: "Эхлэх",
        month: "/сар",
        commission: "Шимтгэл",
        branches: "Салбарууд",
        unlimitedBranches: "{count} хүртэлх салбар",
        upToRooms: "{count} хүртэл өрөө",
        unlimitedRooms: "Хязгааргүй Өрөө",
        bestFor: "{target}-д тохиромжтой",
        digitalBooking: "24/7 Онлайн Захиалга",
        aboutTitle: "Монголын Шөнийн Амьдралд Хувьсгал Хийж Байна",
        aboutSubtitle: "Бид Улаанбаатар хотын энтертайнмент салбарын дижитал дэд бүтцийг бүтээн байгуулж байна.",
        ourMission: "Бидний Эрхэм Зорилго",
        missionText1: "UB Karaoke нь захиалгын үйл явцыг дижитал хэлбэрт шилжүүлэх ганц зорилготойгоор 2026 онд үүсгэн байгуулагдсан. Бид дуулах дуртай хүмүүсийг хотын шилдэг газруудтай холбодог.",
        missionText2: "Газрын эздэд бид өрөөний ашиглалтыг нэмэгдүүлэх, орлогоо хянах, хэрэглэгчдэд орчин үеийн үйлчилгээ үзүүлэх боломжийг олгодог.",
        communityFirst: "Олон Нийт Нэгт",
        communityDesc: "Дуу хөгжим, хамтын туршлагаар хүмүүсийг холбох.",
        innovation: "Инноваци",
        innovationDesc: "Захиалгын платформ ямар байж болох хязгаарыг тэлэх.",
        reliability: "Найдвартай Байдал",
        reliabilityDesc: "Улаанбаатарын хамгийн том караоке сүлжээнүүдийн итгэлийг хүлээсэн.",
        getInTouch: "Холбоо Барих",
        policyTitle: "Үйлчилгээний Нөхцөл & Нууцлал",
        acceptanceTerms: "Нөхцөл Зөвшөөрөх",
        acceptanceText: "UB Karaoke-г ашигласнаар та энэхүү үйлчилгээний нөхцөлийг зөвшөөрч байна. Бид нөхцөлийг урьдчилан мэдэгдэлгүйгээр өөрчлөх эрхтэй.",
        bookingCancellation: "Захиалга & Цуцлах",
        refundPolicyTitle: "Цуцлалт болон Буцаалтын Нөхцөл",
        refundTier1Hours: "Үнэгүй цуцлах хугацаа (цаг)",
        refundTier1HoursDesc: "Энэ хугацаанаас өмнө цуцалбал шимтгэлгүй.",
        refundTier2Hours: "Хэсэгчилсэн буцаалтын хугацаа (цаг)",
        refundTier2HoursDesc: "Энэ хугацаанд цуцалбал хэсэгчилсэн шимтгэлтэй.",
        refundTier2Fee: "Хэсэгчилсэн цуцлалтын шимтгэл (%)",
        refundTier3Fee: "Хоцорч цуцалсан шимтгэл (%)",
        cancellationPolicy: "Төлбөр төлөгдсөнөөр захиалга баталгаажна. Эхлэхээс дор хаяж 24 цагийн өмнө цуцалбал төлбөрийг бүрэн буцаана. 4-24 цагийн өмнө цуцалбал 50% хүртэлх шимтгэл суутгана. 4 цагаас бага хугацаа үлдсэн үед цуцалвал буцаалт хийгдэхгүй.",
        dataPrivacy: "Нууцлал",
        privacyText: "Бид таны хувийн мэдээллийг хүндэтгэнэ. Бид зөвхөн захиалга удирдах зорилгоор нэр, утас, и-мэйл цуглуулдаг. Таны мэдээллийг бусдад дамжуулахгүй.",
        codeOfConduct: "Ёс Зүйн Дүрэм",
        conductText: "Хэрэглэгч байгууллагын эд хөрөнгөд хүндэтгэлтэй хандах үүрэгтэй. Тоног төхөөрөмж (микрофон, дэлгэц г.м) эвдсэн тохиолдолд төлбөрийг хэрэглэгч хариуцна.",
        lastUpdated: "Сүүлд шинэчилсэн: 2026 оны 1 сар",
        iAgreeTo: "Би ",
        termsOfService: "Үйлчилгээний Нөхцөл",
        privacyPolicy: "Нууцлалын Бодлого",
        and: " болон ",
        faqTitle: "Түгээмэл Асуултууд",
        faqSubtitle: "UB Karaoke-ийн талаар таны мэдэх ёстой бүх зүйл.",
        faq1_q: "Би яаж өрөө захиалах вэ?",
        faq1_a: "Нүүр хуудаснаас өөрт тохирох газраа сонгоод, өрөө, цагаа сонгон захиалгаа баталгаажуулна уу.",
        faq2_q: "Захиалгаа цуцалж болох уу?",
        faq2_a: "Тийм ээ, 'Миний захиалгууд' хэсгээс цуцлах боломжтой. 24 цагийн өмнө цуцалбал төлбөр 100% буцаагдана. 4-24 цагийн дотор 50% шимтгэлтэй. 4 цагаас дотогш орсон үед буцаалтгүй.",
        faq3_q: "Би караоке газраа яаж бүртгүүлэх вэ?",
        faq3_a: "'Үнийн санал' хуудас руу орж тохирох багцыг сонгон бүртгүүлнэ үү. Бид 24 цагийн дотор холбогдох болно.",
        faq4_q: "Төлбөр төлөхөд аюулгүй юу?",
        faq4_a: "Тийм ээ, бид QPay, SocialPay зэрэг найдвартай төлбөрийн системүүдийг ашигладаг.",
        faq5_q: "Хөнгөлөлт байдаг уу?",
        faq5_a: "Газар тус бүр өөрийн урамшуулалтай байж болно. 'Онцгой санал' тэмдэглэгээг хараарай.",
        organizationOverview: "Байгууллагын тойм",
        aggregatedStats: "Гүйцэтгэлийн нэгдсэн мэдээлэл:",
        liveStatus: "Шууд төлөв",
        organizationName: "Байгууллагын нэр",
        orgCode: "Байгууллагын код",
        active: "Идэвхтэй",
        inactive: "Идэвхгүй",
        plan: "Багц",
        awaitingApproval: "зөвшөөрөл хүлээж буй",
        branchRevenue: "Салбарын орлого",
        activeBranches: "Идэвхтэй салбарууд",
        quickActions: "Шуурхай үйлдлүүд",
        manualReservation: "Гараар захиалга хийх",
        performanceReport: "Гүйцэтгэлийн тайлан",
        viewBranchStaff: "Салбарын ажилчид",
        manageBookings: "Захиалга удирдах",
        editOrgSettings: "Байгууллагын тохиргоо",
        description: "Тайлбар",
        address: "Хаяг",
        saveChanges: "Хадгалах",
        saving: "Хадгалж байна...",
        assignedBySysadmin: "Систем админ тохируулсан",
        orgDescPlaceholder: "Байгууллагын тухай товч мэдээлэл",
        addressPlaceholder: "Байгууллагын хаяг...",
        creatingInvoice: "QPay нэхэмжлэх үүсгэж байна...",
        amountToPay: "Төлөх дүн",
        scanQrCode: "Банкны аппликейшнээрээ QR кодыг уншуулна уу",
        orOpenBank: "Эсвэл банкны аппаа шууд нээх",
        waitingForPayment: "Төлбөр баталгаажихыг хүлээж байна...",
        retry: "Дахин оролдох",
        paymentSuccess: "Төлбөр амжилттай!",
        cancelBookingHeader: "Захиалга цуцлах",
        cancelBookingMessage: "Та энэ захиалгыг цуцлахдаа итгэлтэй байна уу? Цуцлалтын шимтгэл нэхэмжлэгдэх болно.",
        yesCancel: "Тийм, Цуцлах",
        goBack: "Буцах",
        reservationExpired: "Захиалгын хугацаа дууссан. Дахин оролдоно уу.",
        bookingFailed: "Захиалга амжилтгүй боллоо. Дахин оролдоно уу.",
        roomAlreadyBooked: "Энэ өрөө сонгосон цагт аль хэдийн захиалагдсан байна.",
        processing: "Уншиж байна...",
        staffBookingRestriction: "Ажилтнууд Админ хуудсаар захиалга хийнэ үү.",
        actionRequired: "Төлбөр төлнө үү: Захиалга дуусгах",
        completePaymentNow: "Төлбөр төлөх",
        holdRoomMessage: "Таны өрөөг түр хадгаллаа. Захиалга цуцлагдахаас өмнө шилжүүлэг хийнэ үү.",
        dismissBanner: "Хаах",
        expiresIn: "Төлбөр төлж дуусах хугацаа",
        hurryMessage: "Яараарай! Өрөөгөө баталгаажуулахын тулд төлбөрөө төлнө үү.",
        memberSince: "{year} оноос хойш гишүүн",
        pts: "ОНОО",
        rewards: "Урамшуулал",
        history: "Түүх",
        noAvailableSlots: "Боломжит цаг алга байна.",
        noUpcomingBookings: "Захиалга байхгүй байна",
        roomSelection: "Өрөө сонголт",
        hours: "Цаг",
        payNow: "ТӨЛӨХ",
        timeRemaining: "Үлдсэн хугацаа",
        noBookingHistory: "Түүх байхгүй байна",
        goldTier: "Алтан гишүүн",
        currentBalance: "Одоогийн үлдэгдэл",
        pointsToNextTier: "Дараагийн зэрэглэл хүртэл {points} оноо",
        editProfile: "Профайл засах",
        fullName: "Бүтэн нэр",
        phoneNumber: "Утасны дугаар",
        pleaseLogin: "Нэвтэрнэ үү.",
        backToHome: "Нүүр хуудас руу буцах",
        profileUpdatedSuccess: "Профайл амжилттай шинэчлэгдлээ!",
        profileUpdateFailed: "Профайл шинэчлэхэд алдаа гарлаа: ",
        roomDashboard: "Өрөөний хяналт",
        viewing: "Харагдац",
        signOut: "Гарах",
        noActiveSession: "Идэвхтэй сесс алга",
        tapToFinishCleaning: "Цэвэрлэгээ дууссан бол товшино уу",
        roomControl: "Өрөөний удирдлага",
        schedule: "Хуваарь",
        currentStatus: "Одоогийн төлөв",
        totalBill: "Нийт тооцоо",
        noActiveBookingFound: "Идэвхтэй захиалга олдсонгүй",
        createManualWalkin: "Гар захиалга (Walk-in)",
        checkInGuest: "ЗОЧИН НЭВТРҮҮЛЭХ",
        completeCheckOut: "ДУУСГАХ & ГАРАХ",
        posQuickServices: "Касс (Түргэн үйлчилгээ)",
        addOneHour: "+ 1 Цаг",
        extraMic: "Нэмэлт Mic",
        popularItems: "Түгээмэл бүтээгдэхүүн",
        checkInToEnablePOS: "POS үйлчилгээг идэвхжүүлэхийн тулд зочноо нэвтрүүлнэ үү.",
        yesterday: "Өчигдөр",
        today: "Өнөөдөр",
        tomorrow: "Маргааш",
        week: "Долоо хоног",
        monthLabel: "Сар",
        newWalkinReservation: "Шинэ гар захиалга",
        guestNameOptional: "Зочны нэр (Заавал биш)",
        phoneOptional: "Утас (Заавал биш)",
        createReservation: "Захиалга үүсгэх",
        walkInGuest: "Гар зочин",
        missingInfo: "Мэдээлэл дутуу",
        fillStartTime: "Эхлэх цагийг оруулна уу.",
        itemAdded: "itemAdded",
        addedToOrder: "addedToOrder",
        extended: "Сунгагдлаа",
        bookingExtended: "Захиалга 1 цагаар сунгагдлаа.",
        staffPortalTitle: "АЖИЛТНЫ ХЭСЭГ",
        orgCodeLabel: "Байгууллагын код",
        employeeIdLabel: "Ажилтны ID",
        loginButton: "Нэвтрэх",
        loading: "Ачаалж байна...",
        invalidStaffCredentials: "Байгууллагын код эсвэл ажилтны ID буруу байна.",
        orgNotFound: "Байгууллага олдсонгүй.",
        deviceConfig: "Төхөөрөмжийн тохиргоо",
        staffLoginWelcome: "Салбарын мэдээллээр нэвтэрнэ үү",
        orgSetupHelp: "Байгууллагын мэдээллийг тохируулна уу.",
        accessDeniedStaff: "Хандалт татгалзлаа: Зөвхөн ажилчид нэвтрэх боломжтой.",
        oneTimeSetup: "Нэг удаагийн тохиргоо",
        orgCodeSetupDesc: "Байгууллагын кодыг энд оруулна уу. Энэ төхөөрөмж зөвхөн тухайн байгуулагад хамаарна.",
        deviceConfigSuccess: "Төхөөрөмж амжилттай тохируулагдлаа",
        configCleared: "Тохиргоо устаж цэвэрлэгдлээ",
        clickToSetupOrg: "Байгууллагын код тохируулах",
        deviceNotConfigured: "Төхөөрөмж тохируулаагүй",
        configuredFor: "Салбар:",
        secureLogin: "Нэвтрэх",
        username: "Хэрэглэгчийн нэр",
        passwordPin: "Нууц үг / ПИН код",
        id: "ID",
        selectVenue: "Салбар сонгох",
        createAndConfirm: "Үүсгэх & Баталгаажуулах",
        newManualBooking: "Шинэ гар захиалга",
        bookingCreatedSuccess: "Захиалга амжилттай үүсэж баталгаажлаа!",
        bookingCreateFailed: "Захиалга үүсгэхэд алдаа гарлаа. Боломжит цагийг шалгана уу.",
        approveBookingConfirm: "Энэ захиалгыг зөвшөөрөх үү?",
        rejectBookingConfirm: "Энэ захиалгаас татгалзах уу?",
        auditLogsDesc: "Системийн түүхчилсэн бүртгэл",
        refreshStream: "Шинэчлэх",
        filterByEvent: "Үйлдэлээр шүүх",
        filterByStaff: "Ажилтнаар шүүх",
        allEvents: "Бүх үйлдэл",
        allStaff: "Бүх ажилтан",
        timestamp: "Огноо",
        activity: "Үйлдэл",
        actor: "Гүйцэтгэгч",
        targetEntity: "Объект",
        eventMetadata: "Мэдээлэл",
        pointsLabel: "Оноо",
        globalOverview: "Нийт байгууллагын тойм",
        aggregatedDiagnostics: "Нийт системийн хэмжээнд",
        organizationsLabel: "байгууллага",
        networkStatus: "Сүлжээний төлөв",
        operational: "Хэвийн",
        healthyOperational: "Хэвийн ба ажиллаж байна",
        globalOrganizations: "Нийт байгууллагууд",
        activeEntities: "Идэвхтэй байгууллага",
        platformRevenue: "Нийт орлого",
        totalRegisteredUsers: "Нийт бүртгэлтэй хэрэглэгч",
        pendingInquiries: "Хүлээгдэж буй хүсэлт",
        systemAdministration: "Системийн удирдлага",
        financialCSV: "Санхүүгийн мэдээлэл (CSV)",
        platformSettings: "Системийн тохиргоо",
        globalCommission: "Нийт шимтгэл",
        taxCompliance: "Татварын нийцэл",
        settingsSaved: "Тохиргоо хадгалагдлаа",
        settingsSavedDetail: "Системийн тохиргоо амжилттай шинэчлэгдлээ",
        validationError: "Мэдээлэл дутуу",
        fillAllFields: "Бүх талбарыг бөглөнө үү",
        promoAdded: "Урамшуулал нэмэгдлээ",
        promoCodeCreated: "Урамшууллын код {code} амжилттай үүсгэгдлээ",
        promoAddFailed: "Урамшуулал нэмэхэд алдаа гарлаа",
        promoDeleted: "Урамшуулал устгагдлаа",
        promoRemoved: "Урамшууллын код устгагдлаа",
        systemSettings: "Системийн тохиргоо",
        systemSettingsDesc: "Системийн санхүүгийн үзүүлэлт болон урамшуулал тохируулах",
        financialConfig: "Санхүүгийн тохиргоо",
        vatRate: "НӨАТ-ын хувь",
        multiplierSuffix: " (үржигч)",
        vatExample: "Жишээ: 10% бол 0.10",
        serviceCharge: "Үйлчилгээний хураамж",
        chargeExample: "Стандарт үйлчилгээний хураамжийн коэффициент",
        currencySymbol: "Валютын тэмдэг",
        saveFinancialSettings: "Санхүүгийн тохиргоо хадгалах",
        activePromoCodes: "Идэвхтэй урамшууллын кодууд",
        addNew: "Шинээр нэмэх",
        noActivePromos: "Одоогоор идэвхтэй урамшуулал байхгүй байна",
        off: "хөнгөлөлт",
        validRange: "Хүчинтэй хугацаа: {start} - {end}",
        addNewPromoCode: "Шинэ урамшууллын код нэмэх",
        promoCodeLabel: "Урамшууллын код",
        type: "Төрөл",
        percentage: "Хувь (%)",
        fixedAmount: "Тогтмол дүн",
        value: "Утга",
        startDate: "Эхлэх огноо",
        endDate: "Дуусах огноо",
        createPromotion: "Урамшуулал үүсгэх",
        reportsAnalytics: "Тайлан ба Аналитик",
        reportsAnalyticsDesc: "Байгууллагын гүйцэтгэлийн дэлгэрэнгүй шинжилгээ",
        daily: "Өдрөөр",
        monthly: "Сараар",
        exportPdf: "PDF Татаж авах",
        revenueTrend: "Орлогын чиг хандлага",
        topOperatingRooms: "Шилдэг өрөөнүүд",
        totalBookingsStat: "{count} захиалга",
        repPerformance: "Ажилтны гүйцэтгэл",
        bookingsAssistedStat: "{count} захиалга гүйцэтгэсэн",
        mvp: "MVP",
        unknownRoom: "Үл мэдэгдэх өрөө",
        financeSettlement: "Санхүү ба Төлбөр тооцоо",
        financeSettlementDesc: "Орлого, зарлага болон банкны данс удирдах",
        addBankAccount: "Банкны данс нэмэх",
        totalNetEarnings: "Нийт цэвэр орлого",
        availableForPayout: "Гаргах боломжтой",
        totalPaidOut: "Олгогдсон дүн",
        earningsTab: "Орлого",
        payoutsTab: "Зарлага",
        bankAccountsTab: "Банкны данс",
        gross: "Нийт",
        comm: "Шимтгэл",
        net: "Цэвэр",
        bankAccount: "Банкны данс",
        owner: "Эзэмшигч",
        requestPayoutItems: "{count} үзүүлэлт сонгогдлоо",
        selectBankAccount: "Банкны данс сонгох",
        selectAccountLabel: "Данс сонгох",
        submitRequest: "Хүсэлт илгээх",
        accountHolderName: "Данс эзэмшигчийн нэр",
        bankPlaceholder: "Жишээ: Хаан банк",
        holderPlaceholder: "Нэр оруулна уу",
        numberPlaceholder: "Дансны дугаар оруулна уу",
        setAsDefaultPayout: "Үндсэн дансаар тохируулах",
        requestPayout: "Тооцоо хүсэх",
        pendingPayouts: "Хүлээгдэж буй тооцооны хүсэлтүүд",
        managePayouts: "Тооцоо удирдах",
        payoutManagement: "Тооцооны удирдлага",
        manualPayout: "Гар аргаар тооцоо үүсгэх",
        manualPayoutDesc: "Байгууллагын тооцооны хүсэлтийг гар аргаар үүсгэх.",
        payoutLimit: "Таталт хийх доод хязгаар",
        payoutLimitDesc: "Байгууллага тооцоо хүсэхэд шаардлагатай доод дүн.",
        notificationConfig: "Мэдэгдлийн тохиргоо",
        adminEmailRecipients: "Мэдэгдэл хүлээн авах имэйл хаягууд",
        adminEmailsDesc: "Системийн мэдэгдэл (ж.нь: төлбөрийн хүсэлт) хүлээн авах имэйл хаягуудыг таслалаар тусгаарлаж бичнэ үү.",
        adminEmailsInfo: "Хэрэв хоосон орхивол, 'Систем админ' эрхтэй бүх хэрэглэгч рүү мэдэгдэл илгээгдэнэ.",
        selectionRequired: "Сонгох шаардлагатай",
        payoutItemsSelection: "Зарлага гаргах үзүүлэлтүүдээ сонгоно уу",
        addPayoutAccountFirst: "Эхлээд банкны данс нэмнэ үү",
        saveSystemSettings: "Системийн тохиргоо хадгалах",
        payoutRequestedSuccess: "Зарлагын хүсэлт амжилттай илгээгдлээ",
        payoutRequestFailed: "Зарлагын хүсэлт илгээхэд алдаа гарлаа",
        payoutAccountAdded: "Банкны данс нэмэгдлээ",
        payoutAccountAddFailed: "Банкны данс нэмэхэд алдаа гарлаа",
        payoutMarkedAs: "Зарлагын төлөв {status} боллоо",
        unknownVenue: "Үл мэдэгдэх салбар",
        plansLabel: "Багцууд",
        orgsLabel: "Байгууллагууд",
        systemAdminTitle: "СИСТЕМ АДМИН",
        platformControl: "UB Karaoke Системийн удирдлага",
        accessDeniedSysadminOnly: "Хандах эрх хүрэлцэхгүй. Зөвхөн Систем Админ нэвтрэх боломжтой.",
        returnToPublic: "Нүүр хуудас руу буцах",
        loggingIn: "Нэвтэрч байна...",
        customerCreated: "Хэрэглэгч үүсгэгдлээ",
        customerCreatedDetail: "Хэрэглэгчийн бүртгэл амжилттай үүсгэгдлээ.",
        customerCreateFailed: "Хэрэглэгч үүсгэхэд алдаа гарлаа",
        customerStatusDetail: "Хэрэглэгчийн төлөв {status} боллоо.",
        customerManagement: "Хэрэглэгчийн удирдлага",
        customerManagementDesc: "Платформын нийт хэрэглэгчийн хяналт",
        addCustomer: "Хэрэглэгч нэмэх",
        points: "Оноо",
        noCustomersFoundLabel: "Хэрэглэгч олдсонгүй",
        addNewCustomer: "Шинэ хэрэглэгч нэмэх",
        enterFullName: "Хэрэглэгчийн бүтэн нэр",
        enterUsername: "Нэвтрэх нэр",
        enterEmail: "Имэйл хаяг",
        enterPhone: "Утасны дугаар",
        enterPassword: "Түр нууц үг",
        createCustomer: "Хэрэглэгч үүсгэх",
        newPasswordLabel: "Шинэ нууц үг",
        staffCreated: "Ажилтан үүсгэгдлээ",
        exportReport: "Сар бүрийн тайлан татах",
        selectMonthToExport: "Сар сонгох",
        downloadExcel: "Excel (.xlsx) татах",
        downloadPdf: "PDF (.pdf) татах",
        staffCreatedDetail: "Ажилтны бүртгэл амжилттай үүсгэгдлээ.",
        staffCreateFailed: "Ажилтан үүсгэхэд алдаа гарлаа",
        staffUpdated: "Ажилтан шинэчлэгдлээ",
        staffUpdatedDetail: "Ажилтны мэдээлэл амжилттай шинэчлэгдлээ.",
        staffUpdateFailed: "Ажилтан шинэчлэхэд алдаа гарлаа",
        branchManager: "Салбарын менежер",
        staffMember: "Ажилтан",
        systemAdmin: "Систем админ",
        global: "Глобал",
        staffStatusDetail: "Ажилтны төлөв {status} боллоо.",
        staffManagement: "Ажилчдын удирдлага",
        manageUsersRoles: "Админ болон ажилчдын эрх удирдах",
        filterByOrganization: "Байгууллагаар шүүх",
        addStaff: "Ажилтан нэмэх",
        noStaffFoundLabel: "Ажилчин олдсонгүй",
        addNewStaffMember: "Шинэ ажилтан нэмэх",
        selectRoleLabel: "Албан тушаал сонгох...",
        selectOrganization: "Байгууллага сонгох",
        createStaff: "Ажилтан үүсгэх",
        editStaffMember: "Ажилтан засварлах",
        resetPasswordFor: "{name}-ийн нууц үг шинэчлэх",
        venueDescriptionPlaceholder: "Улаанбаатар хотын дээд зэрэглэлийн караоке.",
        venuePhonePlaceholder: "+976 99000000",
        editType: "Өрөөний төрөл засварлах",
        addType: "Шинэ өрөөний төрөл нэмэх",
        editFeature: "Тоноглол засварлах",
        addFeature: "Шинэ тоноглол нэмэх",
        roomSingular: "Өрөө",
        durationHours: "Хугацаа (цаг)",
        bookingId: "Захиалгын ID",
        noPaymentsFound: "Төлбөрийн мэдээлэл олдсонгүй",
        method: "Төрөл",
        redirectingToHome: "Нүүр хуудас руу шилжиж байна...",
        organizationUpdated: "Байгууллагын мэдээлэл шинэчлэгдлээ.",
        organizationCreated: "Шинэ байгууллага бүртгэгдлээ.",
        failedToSaveOrganization: "Байгууллагын мэдээллийг хадгалахад алдаа гарлаа.",
        failedToUploadLogo: "Лого байршуулахад алдаа гарлаа.",
        clickToCopyId: "ID-г бүрэн хуулах",
        uniqueCode: "Байгууллагын код",
        planStatus: "Төлөв",
        planStart: "Эхлэх огноо",
        planEnd: "Дуусах огноо",
        viewPlanHistory: "Төлөвлөгөөний түүх харах",
        currentPlan: "Одоогийн багц",
        editOrganization: "Байгууллага засварлах",
        newOrganizationHeader: "Шинэ байгууллага бүртгэх",
        internalCodeUnique: "Дотоод код (Давтагдашгүй)",
        selectPlan: "Багц сонгох...",
        planHistoryFor: "{name}-ийн багцын түүх",
        noHistoryFound: "Багцын түүх олдсонгүй",
        commissionRateLabel: "Шимтгэл %",
        planUpdated: "Багцын мэдээлэл шинэчлэгдлээ.",
        planCreated: "Шинэ багц үүсгэгдлээ.",
        failedToSavePlan: "Багц хадгалахад алдаа гарлаа.",
        freeCustom: "Үнэгүй / Тусгай",
        editPlan: "Багц засварлах",
        deletePlan: "Багц устгах",
        subscriptionPlans: "Үйлчилгээний багцууд",
        definePlansDesc: "Байгууллагын үйлчилгээний багцуудыг удирдах",
        createNewPlan: "Шинэ багц үүсгэх",
        monthlyFeeLabel: "Сарын хураамж",
        modifyPlan: "Багц засварлах",
        establishTier: "Шинэ багцын түвшин тогтоох",
        planDisplayName: "Багцын харагдах нэр",
        internalUniqueCode: "Дотоод код",
        monthlyFeeMNT: "Сарын хураамж (₮)",
        platformCommission: "Системийн шимтгэл (%)",
        branchLimit: "Салбарын хязгаар",
        roomCountLimit: "Өрөөний тооны хязгаар",
        updateTier: "Түвшин шинэчлэх",
        createTier: "Түвшин үүсгэх",
        failedToLoadSubscription: "Захиалгын мэдээлэл ачаалахад алдаа гарлаа.",
        subscriptionUpdatedSuccess: "Захиалга амжилттай сунгагдлаа!",
        paymentFailed: "Төлбөр амжилтгүй. Дахин оролдоно уу.",
        planSubscription: "Багц ба Захиалга",
        manageSubDesc: "Байгууллагын багц болон хязгаарыг удирдах",
        currentSubscription: "Одоогийн захиалга",
        standardFree: "Стандарт / Үнэгүй",
        customPricing: "Тусгай үнэ",
        planQuotas: "Багцын хязгаарлалт",
        branchCapacity: "Салбарын багтаамж",
        totalVenuesNote: "* Систем дэх нийт идэвхтэй салбарууд",
        onlineBookings: "Онлайн захиалга",
        prioritySupport: "Давуу эрхтэй тусламж",
        extendOrUpgrade: "Багц сунгах эсвэл ахиулах",
        choosePlanDesc: "Бизнесийн хэрэгцээндээ тохирох багцыг сонгоно уу",
        unlimitedLabel: "Хязгааргүй",
        commissionRateDetail: "{rate}% шимтгэл",
        coreFeaturesInclude: "Бүх удирдлагын боломжууд",
        oneMonth: "1 сар",
        sixMonths: "6 сар",
        securePayment: "Нууцлагдсан төлбөр",
        processingPayment: "Төлбөр боловсруулж байна...",
        commGateway: "Банкны системтэй холбогдож байна",
        planSelection: "Сонгосон багц",
        totalAmount: "Нийт дүн",
        paymentDisclaimer: "БАТЛАХ ТОВЧИЙГ ДАРСНААР ТА {duration} САРЫН ХУГАЦААТАЙ ЗАХИАЛГА СУНГАХЫГ ЗӨВШӨӨРЧ БАЙНА.",
        roomPresentation: "Өрөөний харагдац",
        promotionImage: "Сурталчилгааны зураг",
        roomAmenities: "Өрөөний тоноглол",
        advancedPricing: "Үнийн тохиргоо",
        addPricingRule: "Үнийн дүрэм нэмэх",
        pricingType: "Үнийн төрөл",
        happyHourRecurring: "Хямдралтай цаг (Давтагдах)",
        specificDate: "Тусгай огноо",
        applyTo: "Хамрах өдөр",
        dateRange: "Огнооны муж",
        specialRatePerHour: "Тусгай үнэ (цагаар)",
        priorityLabel: "Их тоо нь өндөр давуу эрхийг илэрхийлнэ",
        noPricingRules: "Энэ өрөөнд үнийн дүрэм тохируулаагүй байна",
        roomRefPlaceholder: "ж.нь Өрөө 101, VIP-1",
        failedToUpdateOrder: "Эрэмбэ шинэчлэхэд алдаа гарлаа",
        failedToAddRule: "Үнийн дүрэм нэмэхэд алдаа гарлаа",
        failedToRemoveRule: "Үнийн дүрэм устгахад алдаа гарлаа",
        pricingRuleAdded: "Үнийн дүрэм нэмэгдлээ",
        pricingRuleRemoved: "Үнийн дүрэм устгагдлаа",
        holidayEvent: "Баяр / Тусгай өдөр",
        recurring: "Давтагдах",
        everyday: "Өдөр бүр",
        weekdays: "Ажлын өдрүүд",
        weekends: "Амралтын өдрүүд",
        roomUpdated: "Өрөө шинэчлэгдлээ",
        roomAdded: "Өрөө нэмэгдлээ",
        venueName: "Салбарын нэр",
        addressPlaceholderDetail: "ж.нь Шангри-Ла Молл, 1 давхарт",
        gmapPlaceholder: "Google Maps линк хуулж тавих",
        customPerDay: "Өдөр бүр өөр",
        dailyAllDays: "Өдөр бүр (Ижил)",
        priceTier: "Үнийн түвшин",
        venueBranding: "Салбарын зураг",
        orLabel: "ЭСВЭЛ",
        selectStockImage: "Галлерейгаас сонгох",
        organizationOwner: "Эзэмшигч байгууллага",
        updateChanges: "Өөрчлөлтийг хадгалах",
        createVenue: "Салбар үүсгэх",
        roomReferenceName: "Өрөөний нэр",
        selectRoomType: "Өрөөний төрөл сонгох...",
        maxCapacity: "Дээд багтаамж",
        enableOnlineBooking: "Онлайн захиалга зөвшөөрөх",
        iconLabel: "Дүрс (Emoji)",
        paymentHistory: "Төлбөрийн түүх",
        refresh: "Шинэчлэх",
        amount: "Дүн",
        branchRoomsInventory: "Салбарын өрөө, тооллого",
        room: "Өрөө",
        ratePerHour: "Цагийн үнэ",
        bookingStatus: "Захиалгын төлөв",
        deleteConfirmation: "Устгах баталгаажуулалт",
        roomCategory: "Өрөөний ангилал",
        physicalAddress: "Байршил, хаяг",
        phoneContact: "Холбоо барих утас",
        openingHours: "Ажиллах цагийн хуваарь",
        bookingSystemSettings: "Захиалгын системийн тохиргоо",
        allowedStartTime: "Онлайн захиалга авч эхлэх цаг",
        allowedEndTime: "Онлайн захиалга авч дуусах цаг",
        maxAdvanceBooking: "Урьдчилсан захиалга (хоногоор)",
        minBooking: "Минимум захиалга (цагаар)",
        maxBooking: "Максимум захиалга (цагаар)",
        uploadCustomImage: "Зураг байршуулах",
        editDetails: "Мэдээлэл засах",
        deactivateRoom: "Өрөө идэвхгүй болгох",
        activateRoom: "Өрөө идэвхжүүлэх",
        editRoom: "Өрөө засах",
        deleteRoom: "Өрөө устгах",
        roomSettings: "Өрөөний тохиргоо",
        noBranchSelected: "Салбар сонгогдоогүй",
        noRoomsFound: "Энэ салбарт өрөө бүртгэгдээгүй байна.",
        selectAmenities: "Тохижилт сонгох",
        seasonalOverride: "Улирлын болон цагийн хямдрал",
        specificDatesOnly: "Зөвхөн товлосон өдрүүдэд (Баяр ёслол)",
        selectDates: "Өдөр сонгох...",
        dates: "Өдрүүд",
        rate: "Үнэ",
        budget: "Төсөвт",
        standard: "Стандарт",
        premium: "Премиум",
        luxury: "Люкс",
        district: "Дүүрэг",
        selectDistrict: "Дүүрэг сонгох",
        resetPassword: "Нууц үг шинэчлэх",
        enterNewPassword: "Шинэ нууц үг оруулна уу",
        passwordResetSuccess: "Нууц үг амжилттай шинэчлэгдлээ",
        statusUpdated: "Төлөв шинэчлэгдлээ",
        organization: "Байгууллага",
        unknown: "Үл мэдэгдэх",
        bookingApproved: "Захиалга амжилттай баталгаажлаа",
        bookingRejected: "Захиалга цуцлагдлаа",
        roomTypes: "Өрөөний төрөл",
        featuresAmenities: "Давуу тал / Хэрэгсэл",
        promoDeleteFailed: "Урамшуулал устгахад алдаа гарлаа",
        standardRoom: "Стандарт өрөө",
        vipLounge: "VIP заал",
        partyHall: "Парти заал",
        minimalSmall: "Минимал/Жижиг",
        bookingOn: "Захиалга нээлттэй",
        bookingOff: "Захиалга хаалттай",
        venueUpdatedSuccess: "Салбар амжилттай шинэчлэгдлээ",
        venueAddedSuccess: "Салбар амжилттай нэмэгдлээ",
        venueRemovedSuccess: "Салбар амжилттай устгагдлаа",
        venueStatusActive: "Салбар идэвхтэй төлөвт шилжлээ",
        venueStatusInactive: "Салбар идэвхгүй төлөвт шилжлээ",
        roomOrderUpdated: "Өрөөний дараалал шинэчлэгдлээ",
        gmapLocationLabel: "GMap байршил (Lat, Long)",
        priority: "Эрэмбэ",
        walkinBookingCreated: "Шууд захиалга үүсгэгдлээ",
        roomNowOccupied: "{name} өрөө ашиглагдаж эхэллээ",
        roomNowCleaning: "{name} өрөөг цэвэрлэж байна",
        roomNowAvailable: "{name} өрөө бэлэн боллоо",
        checkInFailed: "Нэвтрүүлэхэд алдаа гарлаа",
        checkOutFailed: "Гаргахад алдаа гарлаа",
        sengurBottle: "Сэнгүр (Шил)",
        heinekenBottle: "Хэйнекэн (Шил)",
        coke05: "Кока Кола 0.5л",
        water05: "Ус 0.5л",
        mixedNuts: "Самар",
        fruitPlatter: "Жимсний таваг",
        frenchFries: "Шарсан төмс",
        drinks: "Ундаа/Шингэн",
        snacks: "Зууш",
        food: "Хоол",
        available: "Боломжтой",
        occupied: "Ашиглаж буй",
        maintenance: "Засвартай",
        noActivePlan: "ИДЭВХТЭЙ БАГЦГҮЙ",
        expiringSoon: "УДАХГҮЙ ДУУСНА",
        validUntil: "Хүртэл хүчинтэй",
        planId: "Багцын ID",
        proceedToPayment: "Төлбөр төлөх рүү шилжих",
        organizationManagement: "Байгууллагын удирдлага",
        manageEntitiesDesc: "Бизнесийн байгууллагууд болон тохиргоо удирдах",
        newOrganization: "Шинэ байгууллага",
        uploadLogo: "Лого хуулах",
        planHistory: "Багцын түүх",
        copied: "Хуулагдлаа",
        idCopied: "ID түр санах ойд хуулагдлаа",
        resume: "Үргэлжлүүлэх",
        pause: "Зогсоох",
        noBookingsFoundMn: "Захиалга олдсонгүй",
        itemAddedMn: "Бүтээгдэхүүн нэмэгдлээ",
        addedToOrderMn: "захиалгад нэмэгдлээ.",
        unlimited: "Хязгааргүй",
        discard: "Цуцлах",
        // Promotions Management Page
        promotions: "Урамшуулал",
        promotionsPageDesc: "Промо кодуудыг удирдах, ашиглалтыг хянах",
        searchPromoCodes: "Промо код хайх...",
        activeOnly: "Зөвхөн идэвхтэй",
        showingAll: "Бүгдийг харуулах",
        filterByPeriod: "Хугацаагаар шүүх...",
        createFirstPromo: "Эхний промо код үүсгэх",
        noMatchingPromos: "Тохирох промо код олдсонгүй",
        timesUsed: "удаа ашигласан",
        upcoming: "Удахгүй",
        editPromoCode: "Промо код засах",
        editPromoDesc: "Урамшууллын мэдээлэл шинэчлэх",
        addPromoDesc: "Шинэ урамшуулал үүсгэх",
        codeNotEditable: "Промо кодыг үүсгэсний дараа өөрчлөх боломжгүй",
        venuePromoHint: "Салбар сонгох эсвэл 'Бүх салбар'-д хэрэглэх",
        promoUsageHistory: "Промо ашиглалтын түүх",
        allPromos: "Бүх промо кодууд",
        filterByPromo: "Промо кодоор шүүх",
        noPromoBookings: "Промо код ашигласан захиалга байхгүй",
        noResults: "Илэрц олдсонгүй",
        promoCode: "Промо код",
        discount: "Хөнгөлөлт",
        venue: "Салбар",
        edit: "Засах",
        error: "Алдаа",
        confirmDelete: "Устгахыг баталгаажуулна уу",
        promoUpdated: "Шинэчлэгдлээ",
        promoCodeUpdated: "\"{code}\" промо код шинэчлэгдлээ",
        promoUpdateFailed: "Шинэчлэхэд алдаа гарлаа",
        searchVenue: "Салбар хайх...",
        havePromoCode: "Урамшууллын код бий юу?",
        promoApplied: "Урамшуулал ашиглагдлаа!",
        removePromo: "Устгах",
        enterPromoCode: "Код оруулна уу...",
        applyPromo: "Ашиглах",
        promoInvalid: "Урамшууллын код хүчингүй байна",
        identityAvatar: "ХУВИЙН МЭДЭЭЛЭЛ БА АВАТАР",
        profileAvatar: "ПРОФАЙЛ АВАТАР",
        personalDetails: "ХУВИЙН МЭДЭЭЛЭЛ",
        accessSecurity: "ХАНДАЛТ БА АЮУЛГҮЙ БАЙДАЛ",
        contactInformation: "ХОЛБОО БАРИХ МЭДЭЭЛЭЛ",
        roleAssignment: "ЭРХИЙН ТОХИРГОО",
        organizationLink: "БАЙГУУЛЛАГЫН ХОЛБООС",
        identityProfile: "ХУВИЙН МЭДЭЭЛЭЛ",
        security: "АЮУЛГҮЙ БАЙДАЛ",
        onboardingClient: "ШИНЭ ХЭРЭГЛЭГЧ БҮРТГЭХ",
        idNumber: "ДУГААР",
        passwordShort: "НУУЦ ҮГ",
        scheduleAndRoom: "ЦАГ БА ӨРӨӨ",
        pricingAndStatus: "ҮНЭ БА ТӨЛӨВ",
        customerNotes: "ХЭРЭГЛЭГЧИЙН ТЭМДЭГЛЭЛ",
        notProvided: "ӨГӨГДӨӨГҮЙ",
        promoIdentity: "УРАМШУУЛЛЫН МЭДЭЭЛЭЛ",
        rewardCode: "УРАМШУУЛЛЫН КОД",
        discountPolicy: "ХӨНГӨЛӨЛТИЙН НӨХЦӨЛ",
        timeScope: "ХУГАЦАА БА ХАМРАХ ХҮРЭЭ",
        trackingDetail: "БҮХ АМЖИЛТТАЙ АШИГЛАЛТЫГ ХЯНАХ",
        identityBranding: "ХУВИЙН МЭДЭЭЛЭЛ БА БРЭНДИНГ",
        contactLocation: "ХОЛБОО БАРИХ БА БАЙРШИЛ",
        subscriptionPlan: "ГИШҮҮНЧЛЭЛ БА БАГЦ",
        resetPasswordHint: "ХЭРЭГЛЭГЧ ЭНЭ ШИНЭ НУУЦ ҮГЭЭР НЭВТРЭХ ШААРДЛАГАТАЙ",
        confirmReset: "ШИНЭЧЛЭХИЙГ БАТАЛГААЖУУЛАХ",
        notifications: "Мэдэгдэл",
        markAllRead: "Бүгдийг уншсанаар тэмдэглэх",
        noNotifications: "Мэдэгдэл байхгүй байна",
        viewAll: "Бүгдийг харах",
        offline: "Офлайн",
        receiveNotification: "Мэдэгдэл хүлээн авах",

        // Tour Content
        tourNext: "Дараах",
        tourPrev: "Өмнөх",
        tourSkip: "Алгасах",
        tourClose: "Хаах",
        tourDoNotShow: "Дахин харуулахгүй байх",
        tourVenueTitle: "Салбар сонгох",
        tourVenueContent: "Ажилтны порталд тавтай морил! Та өнөөдөр ажиллаж буй салбараа эндээс шалгаж баталгаажуулна уу.",
        tourRoomsTitle: "Өрөөний төлөв",
        tourRoomsContent: "Бүх өрөөний төлөвийг бодит цагт хянах боломжтой. Улаан бол үйлчлүүлэгчтэй, ногоон бол сул гэсэн үг.",
        tourNotificationTitle: "Захиалгын мэдэгдэл",
        tourNotificationContent: "Шинээр орж ирсэн онлайн захиалгуудыг баталгаажуулах эсвэл төлбөр авах тохиолдолд энд мэдэгдэх болно.",
        tourProfileTitle: "Профайл",
        tourProfileContent: "Эндээс та өөрийн профайлыг удирдах болон системээс гарах боломжтой.",

        changeTime: "Цаг өөрчлөх",
        paymentNotConfirmedYet: "Төлбөр хараахан баталгаажаагүй байна. QR-ыг уншуулан төлбөрөө төлнө үү.",
        imAlreadyPaid: "Төлбөр шалгах",
        reschedule: "Дахин товлох",
        bookingRescheduled: "Захиалгын цагийг амжилттай өөрчиллөө!",
        newTime: "Шинэ цаг",
        currentTime: "Одоогийн цаг",
        reschedulesLeft: "Өөрчлөх боломж",
        chooseDateStep: "1. Огноо сонгох",
        chooseTimeStep: "2. Цаг сонгох",
        confirmReschedule: "Цаг өөрчлөх",
        rescheduling: "Өөрчилж байна...",
        rescheduleInfo: "Та захиалгаа 3 хүртэлх удаа өөрчлөх боломжтой. Захиалга эхлэхээс 1 цагийн өмнө, мөн одооноос 2+ цагийн дараах цагийг сонгох ёстой.",
        noSlotsOnDate: "Энэ өдөр боломжтой цаг байхгүй байна.",
        refunds: "Буцаалт",
        refundManagement: "Төлбөрийн буцаалт",
        refundsDesc: "Захиалга цуцлалт болон төлбөрийн буцаалтыг удирдах",
        totalPendingRefunds: "Нийт хүлээгдэж буй",
        processRefund: "Буцаалт хийх",
        refundInitiated: "Буцаалт:",
        refundProcessing: "ажлын 5-7 хоногт багтан шилжигдэх болно.",
        refundAmount: "Буцаах дүн",
        refundFee: "Цуцлалтын шимтгэл",
        payoutRef: "Лавлах",
        markAsProcessed: "Шилжүүлсэн гэж тэмдэглэх",
        markAsProcessedConfirm: "Уг буцаалтыг шилжүүлсэн гэж тэмдэглэх үү?",
        refundProcessedSuccess: "Буцаалтыг шилжүүлсэн гэж тэмдэглэлээ",
        refundCancelled: "Захиалга цуцлагдлаа",
        cancellationConfirmed: "Таны захиалга цуцлагдлаа.",
        refundReason: "Шалтгаан",
        refundDate: "Огноо",
        totalRefunded: "Нийт буцаагдсан",
        completedRefunds: "Дууссан",
        noRefundsFound: "Буцаалт олдсонгүй",
        refundDetails: "Буцаалтын дэлгэрэнгүй",
        customerCancellationRefunds: "ХЭРЭГЛЭГЧИЙН ЦУЦЛАЛТЫН БУЦААЛТ",
        bookingRef: "Захиалгын лавлах",
        markProcessed: "Шилжүүлсэн",

        // Notification Content (Backend mapped)
        "Booking Created": "Захиалга үүслээ",
        "Slot Reserved": "Цаг хүлээлгэнд орлоо",
        "Booking Approved": "Захиалга баталгаажлаа",
        "Booking Rejected": "Захиалга цуцлагдлаа",
        "Checked In": "Нэвтэрсэн",
        "Booking Completed": "Захиалга дууссан",
        "Reservation Expired": "Хүлээлгэний хугацаа дууссан",
        "Payment Reminder": "Төлбөрийн сануулга",
        "New Walk-in Reservation": "Шинээр ирсэн захиалга",
        "Payment Received": "Төлбөр төлөгдлөө",
        "Booking Cancelled": "Захиалга цуцлагдсан",

        "Your booking has been created and is pending approval": "Таны захиалга үүссэн бөгөөд баталгаажихыг хүлээж байна.",
        "Your time slot has been reserved. Complete payment within 15 minutes.": "Таны цаг хүлээлгэнд орлоо. 15 минутын дотор төлбөрөө хийнэ үү.",
        "Your booking has been approved!": "Таны захиалга баталгаажлаа!",
        "Your booking has been rejected": "Таны захиалга цуцлагдлаа.",
        "You have been checked in. Enjoy your session!": "Та амжилттай нэвтэрлээ. Цагийг сайхан өнгөрүүлээрэй!",
        "Your booking is complete. Thank you!": "Үйлчилгээ дууслаа. Баярлалаа!",
        "Your booking reservation has expired": "Таны захиалгын хүлээлгийн хугацаа дууссан байна.",
        "Your reservation expires soon. Complete payment now!": "Хүлээлгийн цаг дуусах дөхлөө. Төлбөрөө яаравчлан төлнө үү!",
        "Manual walk-in booking created": "Газар дээр нь ирсэн хэрэглэгчид шинэ захиалга үүслээ.",
        "Customer has been successfully checked in.": "Үйлчлүүлэгч амжилттай нэвтэрлээ."
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('mn'); // Default to Mongolian

    const t = (key, params = {}) => {
        if (!key) return '';
        let text = dictionaries[language][key] || key;
        if (typeof text !== 'string') return text;
        Object.keys(params).forEach(param => {
            text = text.replace(`{${param}}`, params[param]);
        });
        return text;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'en' ? 'mn' : 'en');
    };

    return (
        <LanguageContext.Provider value={{ language, t, toggleLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};
